function registerPassiveBattleWin(){
 for(const id of state.passiveSkillSlots||[]){
  const sk=SKILLS[id];if(!sk||sk.type!=='passive'||!skillUsable(id))continue;
  const oldLv=skillLevel(id),mult=rebirthProfile().skillMastery;
  let gain=Math.floor(mult),fraction=mult-gain;if(Math.random()<fraction)gain++;gain=Math.max(1,gain);
  state.skillUse[id]=(state.skillUse[id]||0)+gain;const newLv=skillLevel(id);
  if(newLv>oldLv)log(`${sk.name}随实战提升至Lv.${newLv}。`,'sys','system');
  if(newLv>=10&&!state.skillMastered?.[id]){state.skillMastered[id]=true;log(`【被动传承】${sk.name}达到Lv.10，已永久录入人物档案，可跨职业装备。`,'important','important')}
 }
}
function skillReady(id){return (state.skillReadyAt?.[id]||0)<=(state.combatTurn||0)}
function skillCooldownRemaining(id){const ready=state.skillReadyAt?.[id]||0,now=state.combatTurn||0;if(ready<=now)return 0;return Math.max(0,ready-now-1)}
function setSkillCooldown(id){state.skillReadyAt=state.skillReadyAt||{};const passive=passiveSkillTotals(),cd=Math.max(0,(SKILLS[id]?.cooldown||0)-amuletPowers().cooldown-(passive.cooldown||0));state.skillReadyAt[id]=(state.combatTurn||0)+cd+1}
function syncSkillPriority(){syncSkills()}
function moveSkillPriority(id,dir){const arr=state.activeSkillSlots||[],i=arr.indexOf(id),j=i+dir;if(i<0||j<0||j>=arr.length)return;[arr[i],arr[j]]=[arr[j],arr[i]];syncSkills();save();render()}
function skillPriorityRank(id){const i=(state.activeSkillSlots||[]).indexOf(id);return i<0?999:i}
function toggleActiveSkill(id){if(!SKILLS[id]||SKILLS[id].type!=='active'||!skillUsable(id))return;state.activeSkillSlots=state.activeSkillSlots||[];const i=state.activeSkillSlots.indexOf(id);if(i>=0)state.activeSkillSlots.splice(i,1);else{if(state.activeSkillSlots.length>=3)return alert('主动技能槽最多3个，请先卸下一个。');state.activeSkillSlots.push(id)}syncSkills();save();render()}
function togglePassiveSkill(id){if(!SKILLS[id]||SKILLS[id].type!=='passive'||!skillUsable(id))return;state.passiveSkillSlots=state.passiveSkillSlots||[];const i=state.passiveSkillSlots.indexOf(id);if(i>=0)state.passiveSkillSlots.splice(i,1);else{if(state.passiveSkillSlots.length>=2)return alert('被动技能槽最多2个，请先卸下一个。');state.passiveSkillSlots.push(id)}syncSkills();save();render()}
function equipNativeClassSet(styleId=state.style){if(styleId!==state.style)return;state.activeSkillSlots=nativeActiveSkills(styleId).slice(0,3);state.passiveSkillSlots=nativePassiveSkills(styleId).slice(0,2);syncSkills();save();render()}
function skillEffectText(id){const sk=SKILLS[id],lv=skillLevel(id),p=skillPower(id),pct=n=>Math.round(n*100);if(sk.type==='passive'){const names={hpPct:'生命',mpPct:'法力',atkPct:'攻击',defPct:'防御',speedPct:'速度',crit:'原始暴击',critDmg:'暴击伤害',skillChance:'技能触发',bossDamage:'Boss伤害',lifesteal:'吸血',cooldown:'冷却',healing:'治疗',ignoreDef:'无视防御'},scale=passiveScale(id);return Object.entries(sk.effects||{}).map(([k,v])=>{if(k==='cooldown')return `${names[k]}-${Math.round(v)}`;if(k==='crit')return `${names[k]}+${(v*scale).toFixed(1)}`;return `${names[k]}+${Math.round(v*scale*100)}%`}).join(' · ')}if(sk.kind==='damage')return `${sk.hits||1}段，单段${pct(sk.mult*p)}%伤害${sk.ignore?`，无视${pct(sk.ignore)}%防御`:''}`;if(sk.kind==='drain')return `造成${pct(sk.mult*p)}%伤害，吸血${pct(sk.drain*(1+(lv-1)*.03))}%`;if(sk.kind==='execute')return `常规${pct(sk.mult*p)}%伤害；敌人≤${pct(sk.executeThreshold)}%生命时${pct(sk.executeMult*p)}%`;if(sk.kind==='debuff')return `${pct(sk.mult*p)}%伤害，并降低敌人${pct(sk.debuffArmor)}%防御${sk.debuffTurns}回合`;if(sk.kind==='reduce')return `本次伤害降低${Math.min(85,pct(sk.reduce*p))}%`;if(sk.kind==='counter')return `受击后反击，造成${pct(sk.counterMult*p)}%攻击伤害`;if(sk.kind==='heal')return `生命低于${pct(sk.threshold)}%时治疗，效果×${p.toFixed(2)}${sk.mp?`，法力${sk.mp}`:''}`;if(sk.kind==='mirror')return `减伤${Math.min(85,pct(sk.reduce*p))}%，反射${pct(sk.reflect*p)}%实际伤害`;return `效果×${p.toFixed(2)}`}
function tryDropSpecialSkill(){return false}
const TITLES={novice:{name:'初入无尽',desc:'经验+5%。',unlock:s=>s.totalKills>=10,mods:{xp:1.05}},hunter:{name:'百兽猎手',desc:'装备掉率+12%，金币-8%。',unlock:s=>s.totalKills>=100,mods:{drop:1.12,gold:.92}},challenger:{name:'越级者',desc:'挑战高CP怪物时经验+20%。',unlock:s=>s.highRiskWins>=20,mods:{riskXp:1.2}},breeder:{name:'灵宠培育者',desc:'Boss宠物掉率+15%，自身攻击-5%。',unlock:s=>s.pets.length>=3,mods:{pet:1.15,atk:.95}},reborn:{name:'轮回者',desc:'所有基础属性+3%。',unlock:s=>s.rebirths>=1,mods:{all:1.03}}};
const PET_TYPE_IDS=['Attack','Defense','Magic','Balance'];
const PET_TYPES={Attack:{name:'攻击型',growth:{hp:7,atk:3.2,def:.65,magic:.5},desc:'高物理输出；每3次行动发动撕裂并施加破甲。',role:'输出 / 破甲'},Defense:{name:'防御型',growth:{hp:14,atk:1.3,def:2.1,magic:.5},desc:'高生命与防御；容易成为攻击目标，并主动分担玩家伤害。',role:'承伤 / 护主'},Magic:{name:'施法型',growth:{hp:8,atk:1,def:.8,magic:2.8},desc:'每3次行动根据战况治疗玩家或宠物，否则削弱敌人。',role:'治疗 / 减益'},Balance:{name:'平衡型',growth:{hp:10,atk:2,def:1.25,magic:1.4},desc:'稳定输出；每4次行动回复双方并提高玩家攻击。',role:'输出 / 增益'}};
const PET_SPECIES={'灰尾幼狼':{archetype:'迅捷猎手',preferred:['Attack','Balance'],focus:'力量 ＞ 体魄 ＞ 守护',desc:'来自新月草原的群猎幼狼，擅长追击残血目标。适合培养为持续物理输出或协同输出。',trait:'猎杀本能',traitDesc:'敌人生命低于35%时，自身造成的伤害提高25%。',skill:'月影扑杀',skillDesc:'每5次行动追加一次强力扑杀，并短暂撕开敌人防御。'},'裂风幼狮':{archetype:'首领猎手',preferred:['Attack','Defense'],focus:'力量 / 体魄 ＞ 守护',desc:'裂风丘陵狮群的幼崽，对大型目标具有天然压迫力。适合Boss战、强攻或前排路线。',trait:'王兽本能',traitDesc:'面对区域Boss时，自身伤害提高12%。',skill:'裂风咆哮',skillDesc:'每5次行动造成额外伤害，并使敌人攻击降低20%，持续2回合。'},'树灵幼芽':{archetype:'续航核心',preferred:['Magic','Defense'],focus:'灵性 ＞ 体魄 ＞ 守护',desc:'魂木森林孕育的幼生树灵，恢复能力突出。适合治疗、续航与持久Boss战。',trait:'根系再生',traitDesc:'每次行动后恢复自身2%最大生命。',skill:'萌芽回春',skillDesc:'每4次行动同时治疗玩家和自身，低血量战斗价值很高。'},'霜鳍幼兽':{archetype:'控制守护',preferred:['Defense','Magic'],focus:'守护 / 灵性 ＞ 体魄',desc:'霜蚀海岸的耐寒幼兽，能够削弱敌人攻势。适合防御、减益和稳定推进。',trait:'寒霜皮甲',traitDesc:'自身受到的伤害降低12%。',skill:'寒霜吐息',skillDesc:'每4次行动造成灵能伤害，并使敌人攻击降低10%，持续2回合。'},'王魂侍从':{archetype:'契约护卫',preferred:['Defense','Balance'],focus:'体魄 / 守护 ＞ 灵性',desc:'失落王城残存的守誓灵体，擅长保护契约者。适合护主、减伤和平衡辅助。',trait:'王魂守誓',traitDesc:'存活出战时，玩家受到的直接伤害降低5%。',skill:'王魂庇护',skillDesc:'每5次行动赋予玩家2次强化防护，使受到的伤害额外降低20%。'},'星核幼龙':{archetype:'终局爆发',preferred:['Attack','Magic','Balance'],focus:'力量 / 灵性 ＞ 体魄',desc:'星渊孕育的幼龙，拥有极高的混合输出潜力。适合终局攻击、施法或平衡构筑。',trait:'星核共鸣',traitDesc:'自身所有伤害提高10%。',skill:'星核吐息',skillDesc:'每4次行动追加一次高额混合伤害，并无视60%敌人防御。'}};
function petSpeciesData(p){return PET_SPECIES[p?.name]||{archetype:'未知生态',preferred:[],focus:'按当前类型培养',desc:'尚未记录该物种生态。',trait:'未知特性',traitDesc:'无',skill:'未知技能',skillDesc:'无'}}
function petBuildFit(p){const d=petSpeciesData(p),fit=d.preferred.includes(p.type);return `${fit?'契合':'偏门'}｜${PET_TYPES[p.type].name}：${PET_TYPES[p.type].role}｜推荐资质 ${d.focus}`}
function petCombatPower(p){const s=petStats(p),ib=petTierInstincts(p);let raw=s.maxHp*.28+s.atk*4.2+s.def*4.5+s.magic*4.0;let factor=ib.damage*(1+(ib.speciesSkill-1)*.35)*(1+(1/ib.damageTaken-1)*.45)*(1+ib.regen*4)*(1+(ib.bossDamage-1)*.25);if(p.name==='灰尾幼狼')factor*=1.05;else if(p.name==='裂风幼狮')factor*=1.04;else if(p.name==='树灵幼芽')factor*=1.08;else if(p.name==='霜鳍幼兽')factor*=1.07;else if(p.name==='王魂侍从')factor*=1.08;else if(p.name==='星核幼龙')factor*=1.10;return Math.round(raw*factor)}
function petInstinctScale(p){return 1+.02*Math.max(0,(p?.tier||1)-1)}
function petTraitScale(p){return 1+.03*Math.max(0,(p?.tier||1)-1)}
function petExclusiveSkillScale(p){return 1+.04*Math.max(0,(p?.tier||1)-1)}
function petScaledTraitText(p){const x=petTraitScale(p),d=petSpeciesData(p);if(p.name==='灰尾幼狼')return `敌人生命≤35%时伤害+${Math.round(25*x)}%。`;if(p.name==='裂风幼狮')return `对区域Boss伤害+${Math.round(12*x)}%。`;if(p.name==='树灵幼芽')return `每次行动后恢复${(2*x).toFixed(1)}%最大生命。`;if(p.name==='霜鳍幼兽')return `受到伤害降低${Math.min(45,12*x).toFixed(1)}%。`;if(p.name==='王魂侍从')return `存活时玩家受到直接伤害降低${Math.min(25,5*x).toFixed(1)}%。`;if(p.name==='星核幼龙')return `自身全部伤害+${Math.round(10*x)}%。`;return d.traitDesc}
function petScaledSkillText(p){const x=petExclusiveSkillScale(p),d=petSpeciesData(p);return `${d.skillDesc}｜当前阶级技能强度×${x.toFixed(2)}`}
function petScaledInstinctText(p){return `${petTierInstinctText(p)}｜阶级本能强度×${petInstinctScale(p).toFixed(2)}`}
function petSpeciesDamageMult(p,e){let m=1,ts=petTraitScale(p);if(p.name==='灰尾幼狼'&&e&&e.hp/e.maxHp<=.35)m*=1+.25*ts;if(p.name==='裂风幼狮'&&e?.boss)m*=1+.12*ts;if(p.name==='星核幼龙')m*=1+.10*ts;const ib=petTierInstincts(p);m*=ib.damage;if(e?.boss)m*=ib.bossDamage*(1+amuletPowers().bossDamage);return m}
function petDamageTakenMult(p){const ts=petTraitScale(p),species=p?.name==='霜鳍幼兽'?1-Math.min(.45,.12*ts):1;return species*petTierInstincts(p).damageTaken}
function playerDamageTakenPetMult(p){if(!(p?.name==='王魂侍从'&&petAlive(p)))return 1;return 1-Math.min(.25,.05*petTraitScale(p))}
function petSpeciesAfterAction(p){if(!p||!petAlive(p))return;const ps=petStats(p),ib=petTierInstincts(p),is=petInstinctScale(p),ts=petTraitScale(p);let pct=ib.regen*is;if(p.name==='树灵幼芽')pct+=.02*ts;if(pct>0){const h=Math.max(1,Math.round(ps.maxHp*pct));p.hp=Math.min(ps.maxHp,p.hp+h)}}
