function itemText(it){const mult=1+(it.refine||0)*.08,tier=inferItemTier(it),names={str:'力量',int:'智力',dex:'敏捷',will:'意志',luck:'幸运',hp:'生命',mp:'法力',crit:'暴击',def:'防御',atk:'攻击'};let parts=[];if(Array.isArray(it.affixes)&&it.affixes.length){parts=it.affixes.map(a=>`${names[a.stat]||a.stat}+${Math.round((a.value||0)*mult)}`);if(it.slot==='weapon'&&(it.stats?.atk||0)>0)parts.unshift(`攻击+${Math.round((it.stats.atk||0)*mult)}`);if(it.slot==='armor'&&(it.stats?.def||0)>0){const affDef=it.affixes.filter(a=>a.stat==='def').reduce((n,a)=>n+(a.value||0),0),baseDef=Math.max(0,(it.stats.def||0)-affDef);if(baseDef>0)parts.unshift(`基础防御+${Math.round(baseDef*mult)}`)}}else parts=Object.entries(it.stats||{}).map(([k,v])=>`${names[k]||k}+${Math.round(v*mult)}`);return `${tier}阶${it.sourceMapName?` · ${it.sourceMapName}`:''}${it.sourceThreat?`T${it.sourceThreat}`:''}${it.refine?` / 精炼+${it.refine}`:''} / ${parts.join(' / ')}${it.weaponType?` / ${WEAPON_TYPES[it.weaponType].desc}`:''}${Array.isArray(it.arcanes)&&it.arcanes.length?` / ${it.arcanes.map(amuletArcaneText).join(' / ')}`:''}`}
function receiveItem(it){if(it.rarity<state.autoSell){state.gold+=itemSellValue(it);log(`自动出售 ${it.name}，金币+${itemSellValue(it)}。`,'loot');return}if(state.inventory.length>=state.inventoryCapacity){const low=state.inventory.filter(x=>!x.locked).sort((a,b)=>inventoryUpgradeDelta(a)-inventoryUpgradeDelta(b)||itemScore(a)-itemScore(b))[0];if(low&&inventoryUpgradeDelta(it)>inventoryUpgradeDelta(low)){sellItem(low.id,false);state.inventory.push(it);log(`背包已满，出售提升价值更低的装备并保留 ${it.name}。`,'loot')}else{state.gold+=itemSellValue(it);log(`背包已满，自动出售 ${it.name}。`,'loot')}}else{state.inventory.push(it);log(`获得 ${it.name}：${itemText(it)}。`,'loot')}}
function ensureBossCycle(id=state.mapId){state.bossCycles=state.bossCycles||{};const c=state.bossCycles[id]||{normalSinceBoss:0,retryCountdown:0,bossEncounters:0,bossWins:0,threatTier:0,threatUnlocked:0,dangerFail:0,warningIssued:false};const cap=threatCap(id),limit=Number.isFinite(cap)?cap:999;if(c.threatTier===undefined)c.threatTier=0;if(c.threatUnlocked===undefined)c.threatUnlocked=Math.max(Number(c.threatTier||0),Math.min(limit,Number(c.bossWins||0)));c.threatUnlocked=clamp(Math.round(Number(c.threatUnlocked)||0),0,limit);c.threatTier=clamp(Math.round(Number(c.threatTier)||0),0,c.threatUnlocked);c.dangerFail=Math.max(0,Number(c.dangerFail)||0);c.warningIssued=!!c.warningIssued;state.bossCycles[id]=c;return c}
function threatCap(id=state.mapId){const m=MAPS.find(x=>x.id===id);return m?.threatCap??0}
function threatTier(id=state.mapId){return ensureBossCycle(id).threatTier||0}
function threatUnlocked(id=state.mapId){return ensureBossCycle(id).threatUnlocked||0}
function threatCapText(id=state.mapId){const cap=threatCap(id);return Number.isFinite(cap)?`上限T${cap}`:'无限危险度'}
function dangerEffectiveCap(id=state.mapId){const cap=threatCap(id);return Number.isFinite(cap)?Math.max(1,cap):12}
function dangerProgress(id=state.mapId){return clamp(threatTier(id)/dangerEffectiveCap(id),0,1)}
function dangerDropProfile(id=state.mapId){const t=threatTier(id),p=dangerProgress(id),rp=rebirthProfile();return{progress:p,maxed:Number.isFinite(threatCap(id))&&t>=threatCap(id),gearDrop:Math.min(2,1+.18*t/(1+.06*t))*rp.gearDrop,petDrop:Math.min(1.8,1+.10*t/(1+.05*t))*rp.petDrop,mythic:Math.min(3.2,1+.22*t)*rp.mythic,mutation:Math.min(2.2,1+.12*t)*rp.mutation,identity:Math.min(1.75,1+.08*t)}}
function worldCombatScale(id=state.mapId){const t=threatTier(id);return{tier:t,cpMult:Math.sqrt((1+.19*t+.06*t*t)*(1+.115*t+.035*t*t)*(1+.08*t+.02*t*t)),hp:1+.19*t+.06*t*t,atk:1+.115*t+.035*t*t,def:1+.08*t+.02*t*t,speed:1+.025*t,reward:1+.12*t,levelBonus:Math.floor(t/3)}}
function threatScale(id=state.mapId){return{...worldCombatScale(id),...dangerDropProfile(id)}}
function effectiveMapCp(mapDef){return Math.round(mapDef.cp*worldCombatScale(mapDef.id).cpMult)}
function rollMonsterTitle(tier=0){return pickWeighted(MONSTER_TITLES)}
function bossCycleConfig(id=state.mapId){const threat=threatTier(id),timeLv=Math.min(REBIRTH_LAW_MAX,ensureRebirthLaws().time||0),base=Math.max(0,50-threat*5),timeReduce=timeLv*2,amuletReduce=amuletPowers().bossNeed||0,period=Math.max(0,base-timeReduce-amuletReduce);return{threat,timeLv,base,timeReduce,period,retry:Math.ceil(period/2),amuletReduce}}
function bossEncounterChance(id=state.mapId){const c=ensureBossCycle(id),cfg=bossCycleConfig(id);if(state.bossProgress?.[id]?.active)return c.retryCountdown<=0?1:0;return c.normalSinceBoss>=cfg.period?1:0}
function shouldEncounterBoss(id=state.mapId){const c=ensureBossCycle(id),progress=state.bossProgress?.[id],cfg=bossCycleConfig(id);if(progress?.active)return c.retryCountdown<=0;return c.normalSinceBoss>=cfg.period}
function bossTacticalHint(id=state.mapId){return{meadow:'低于35%生命后狂暴：需要稳定生存或尽快收尾。',hill:'每4回合发动裂风扑杀：防御宠物和减伤技能更有效。',forest:'每4回合恢复生命：需要爆发、破甲或处决。',shore:'拥有额外高防御：优先穿透、破甲和魔法爆发。',ruins:'每5回合生成王魂护盾：多段攻击可先破盾。',abyss:'每3回合吞噬法力：降低技能耗魔或提高普通攻击强度。'}[id]||'观察首领机制并调整构筑。'}
function bossEncounterText(id){const c=ensureBossCycle(id),progress=state.bossProgress?.[id],cfg=bossCycleConfig(id);if(progress?.active){const tries=Number(progress.attempts||0);return c.retryCountdown>0?`狩猎挑战${tries}/3：再击败${c.retryCountdown}只普通怪后重遇`:`狩猎挑战${tries}/3：受伤Boss将在下一场重现`}return `Boss周期 ${cfg.period}只｜进度 ${Math.min(c.normalSinceBoss,cfg.period)}/${cfg.period}｜还需${Math.max(0,cfg.period-c.normalSinceBoss)}只`}
function makeEnemy(forceBoss=false){const m=map(),boss=forceBoss,w=worldCombatScale(m.id),region=Math.max(1,m.cp/MAPS[0].cp),title=boss?{name:'区域首领：',atkMul:1.7,hpMul:16,defMul:1.25,xp:5,gold:7,drop:4.5}:rollMonsterTitle(),baseLevel=boss?m.levels[1]+2:rnd(m.levels[0],m.levels[1]),lv=baseLevel+w.levelBonus,rawHp=(72+lv*11)*Math.pow(region,.65),rawAtk=(11+lv*1.45)*Math.pow(region,.33),rawDef=(2.5+lv*.50)*Math.pow(region,.22),rawSpeed=(7+lv*.42)*Math.pow(region,.07),maxHp=Math.round(rawHp*(title.hpMul||1)*w.hp),atk=Math.round(rawAtk*(title.atkMul||1)*w.atk),def=Math.round(rawDef*(title.defMul||1)*w.def),speed=Math.round(rawSpeed*w.speed),titleCp=Math.sqrt((title.hpMul||1)*(title.atkMul||1))*Math.pow(title.defMul||1,.25);let enemy={id:'e'+Date.now()+Math.random(),name:`${title.name}${boss?m.boss:m.monsters[rnd(0,m.monsters.length-1)]}`,boss,title,level:lv,mapId:m.id,round:0,enraged:false,shield:0,threatTier:threatTier(m.id),bossCyclePeriod:boss?bossCycleConfig(m.id).period:0,maxHp,hp:maxHp,huntStartHp:maxHp,atk,def,speed,cp:Math.round(m.cp*w.cpMult*titleCp),xp:title.xp,gold:title.gold,drop:title.drop,rewardMult:w.reward};if(boss&&m.id==='shore')enemy.def=Math.round(enemy.def*1.32);return enemy}
function ensureEnemy(){if(state.enemy)return;prepareNewBattle();const m=map(),cycle=ensureBossCycle(m.id),progress=state.bossProgress[m.id],boss=shouldEncounterBoss(m.id);if(boss){state.enemy=makeEnemy(true);if(progress?.active){const storedPeriod=Number(progress.encounterPeriod);state.enemy.bossCyclePeriod=Math.max(0,Number.isFinite(storedPeriod)?storedPeriod:Number(state.enemy.bossCyclePeriod||0));if(Number.isFinite(progress.hpRatio)){state.enemy.hp=Math.max(1,Math.round(state.enemy.maxHp*clamp(progress.hpRatio,0,1)))}else{state.enemy.maxHp=progress.maxHp;state.enemy.hp=progress.hp}state.enemy.huntStartHp=state.enemy.hp;progress.hp=state.enemy.hp;progress.maxHp=state.enemy.maxHp;log(`再次遭遇受伤的区域首领 ${state.enemy.name}，挑战${Number(progress.attempts||0)+1}/3，剩余生命${Math.round(state.enemy.hp)}/${state.enemy.maxHp}。`,'important','important')}else{cycle.bossEncounters++;cycle.warningIssued=false;log(`区域首领 ${state.enemy.name} 出现。机制：${bossTacticalHint(m.id)}`,'important','important')}}else state.enemy=makeEnemy(false)}
function activePet(){return state.pets.find(p=>p.id===state.activePetId)||null}
function setActivePet(id){const p=state.pets.find(x=>x.id===id);if(!p)return;if(state.running&&state.enemy)return alert('请先暂停战斗，再更换出战宠物。');state.activePetId=id;const ps=petStats(p);p.hp=ps.maxHp;p.battleTurns=0;p.fallen=false;state.temp=state.temp||{};state.temp.petGuardTurns=0;state.temp.petAtkBuffTurns=0;state.temp.petAtkBuff=0;log(`${p.name}成为新的出战宠物。`,'sys');render()}
function petAlive(p=activePet()){return !!p&&Number(p.hp)>0&&!p.fallen}
function petRoleStatus(p=activePet()){if(!p)return'';const type=PET_TYPES[p.type],sp=petSpeciesData(p);if(!petAlive(p))return`${sp.archetype} / ${type.role}｜本场已倒下`;if(p.type==='Defense'&&state.temp?.petGuardTurns>0)return`${sp.archetype} / ${type.role}｜守护剩余${state.temp.petGuardTurns}次受击`;if(p.type==='Balance'&&state.temp?.petAtkBuffTurns>0)return`${sp.archetype} / ${type.role}｜协同增益剩余${state.temp.petAtkBuffTurns}次攻击`;return `${sp.archetype} / ${type.role}`}
function enemyDefenseAgainstCompanion(e){let mult=1;if((e.petArmorBreakTurns||0)>0)mult*=.78;if((e.petWeakenTurns||0)>0)mult*=.90;return e.def*mult}
function markPetFallen(p){if(!p||p.fallen)return;p.hp=0;p.fallen=true;log(`${p.name}生命归零，本场暂时无法继续行动；下一场会自动复活。`,'lose')}
function tickCompanionEffects(e){if(!e)return;['petArmorBreakTurns','petWeakenTurns','skillArmorBreakTurns','speciesWeakenTurns','frostbiteTurns'].forEach(k=>{if((e[k]||0)>0)e[k]--})}
function petStats(p){const g=PET_TYPES[p.type].growth,a=migratePetAptitudes(p),tm=petTierMult(p.tier||1),xm=p.mutant?PET_MUTANT_MULT:1,rp=rebirthProfile(),ib=petTierInstincts(p),all=ib.all;return{maxHp:Math.round((p.baseHp+g.hp*p.level)*PET_GRADE_MULT[a.hp]*tm*xm*ib.hp*all),atk:Math.round((p.baseAtk+g.atk*p.level)*PET_GRADE_MULT[a.atk]*tm*xm*rp.petPower*(raceTraitPowers().petPower||1)*ib.atk*all),def:Math.round((p.baseDef+g.def*p.level)*PET_GRADE_MULT[a.def]*tm*xm*ib.def*all),magic:Math.round((p.baseMagic+g.magic*p.level)*PET_GRADE_MULT[a.magic]*tm*xm*rp.petPower*(raceTraitPowers().petPower||1)*ib.magic*all)}}
function rollPetType(){return PET_TYPE_IDS[Math.floor(Math.random()*PET_TYPE_IDS.length)]}
const PET_SPECIES_ICONS={'灰尾幼狼':'🐺','裂风幼狮':'🦁','树灵幼芽':'🌱','霜鳍幼兽':'🐬','王魂侍从':'👻','星核幼龙':'🐉'};
function petSpeciesIcon(p){return PET_SPECIES_ICONS[p?.name]||'🐾'}
function petPortrait(p){if(!p)return '';return `<div class="pet-portrait ${p.mutant?'mutant':''}" title="${p.name}">${petSpeciesIcon(p)}<small>${p.tier||1}阶</small></div>`}
function itemVisualClass(it){return it?.rarity===5?'mythic-item':''}
function petTypeIcon(type){return type==='Attack'?'🐺':type==='Defense'?'🐢':type==='Magic'?'🦉':'🦊'}
function petTypeCounts(){const counts={Attack:0,Defense:0,Magic:0,Balance:0};state.pets.forEach(p=>counts[p.type]=(counts[p.type]||0)+1);return counts}
function rollPetMutation(mapDef=map()){const luck=stats().luck,d=dangerDropProfile(mapDef.id),base=Math.min(.009,.0025+luck*.000012);return Math.random()<Math.min(.014,base*d.mutation)}
function petVariantLabel(p){return p?.mutant?'<span class="mutant-x">变异 X</span>':'普通种'}
function petKeepScore(p){return (p?.mutant?1000000:0)+petCombatPower(p)*10+petOverallScore(p)*100+(p?.level||1)*5+Math.round(petEvolutionProgress(p)*3000)}
