function createPet(name,type,mapIndex){const m=MAPS[mapIndex]||map(),tier=rollPetTier(m),mutant=rollPetMutation(m),p={id:'p'+state.nextId++,name,baseSpecies:petBaseSpecies(name),type,tier,mutant,mutationGrade:mutant?'X':null,level:1,xp:0,evolutionXp:0,fusionInvestedXp:mutant?100:1,aptitudes:rollPetAptitudes(type,mapIndex),baseHp:34,baseAtk:5,baseDef:2,baseMagic:3,hp:1,locked:false,battleTurns:0,fallen:false};p.hp=petStats(p).maxHp;return p}
function petDustValue(p){const base=(PET_DUST_VALUES[petOverallGrade(p)]||4)+Math.floor(p.level/5)+(p.tier||1)*2;return p.mutant?base*8:base}
function bestReplacementPet(excludeId=null){return state.pets.filter(p=>p.id!==excludeId&&!p.locked).sort((a,b)=>petKeepScore(b)-petKeepScore(a))[0]||state.pets.filter(p=>p.id!==excludeId).sort((a,b)=>petKeepScore(b)-petKeepScore(a))[0]||null}
function activateReplacement(excludeId=null){const next=bestReplacementPet(excludeId);state.activePetId=next?next.id:null;if(next){const ps=petStats(next);next.hp=ps.maxHp;next.fallen=false;next.battleTurns=0}return next}
function removePet(id){const i=state.pets.findIndex(p=>p.id===id);if(i<0)return null;return state.pets.splice(i,1)[0]}
function releasePet(id,ask=true){const p=state.pets.find(x=>x.id===id);if(!p)return alert('找不到这只宠物。');if(p.locked)return alert('该宠物已锁定，请先解锁后再放归。');const wasActive=p.id===state.activePetId,value=petDustValue(p),warning=p.mutant?'\n\n【警告】这是红色变异X宠物，掉落极低。':'';if(ask&&!confirm(`放归${p.tier||1}阶${p.mutant?'变异X ':''}${p.name}[${petOverallGrade(p)}]？\n宠物会永久消失，并获得${value}灵宠精华。${wasActive?'\n这是当前出战宠物，放归后会自动选择其他宠物出战。':''}${warning}`))return false;removePet(id);state.petDust+=value;const next=wasActive?activateReplacement(id):activePet();log(`放归${p.mutant?'变异X ':''}${p.name}[${petOverallGrade(p)}]，灵宠精华+${value}${wasActive?(next?`，${next.name}自动接替出战`:'，当前没有出战宠物'):''}。`,'loot');render();return true}
function feedPet(id,ask=true){const material=state.pets.find(x=>x.id===id);if(!material)return alert('找不到经验素材宠物。');if(material.locked)return alert('该宠物已锁定，请先解锁后再进行经验转化。');let target=activePet();if(!target||target.id===material.id)target=bestReplacementPet(material.id);if(!target)return alert('至少需要另一只宠物作为经验接收目标。当前只有这一只宠物，不能转化。');const xp=16+petOverallScore(material)*8+material.level*4+(material.tier||1)*8,wasActive=material.id===state.activePetId,warning=material.mutant?'\n\n【警告】素材是红色变异X宠物，掉落极低。':'';if(ask&&!confirm(`经验转化预览：\n素材：${material.tier||1}阶 ${material.mutant?'变异X ':''}${material.name}[${petOverallGrade(material)}]\n目标：${target.tier||1}阶 ${target.mutant?'变异X ':''}${target.name}[${petOverallGrade(target)}]\n获得经验：${xp}\n\n素材宠物会永久消失。${warning}`))return false;removePet(id);petGainXp(target,xp);if(wasActive){state.activePetId=target.id;const ps=petStats(target);target.hp=ps.maxHp;target.fallen=false;target.battleTurns=0}log(`${material.mutant?'变异X ':''}${material.name}[${petOverallGrade(material)}]已转化为经验，${target.name}经验+${xp}${wasActive?'并接替出战':''}。`,'loot');render();return true}
function bestAptitudeInheritance(target,donor){if(!target||!donor||!samePetSpecies(target,donor))return null;const ta=migratePetAptitudes(target),da=migratePetAptitudes(donor),gains=[];Object.keys(ta).forEach(stat=>{const gap=gradeIndex(da[stat])-gradeIndex(ta[stat]);if(gap>0)gains.push({stat,from:ta[stat],to:da[stat],gap})});gains.sort((a,b)=>b.gap-a.gap||gradeIndex(b.to)-gradeIndex(a.to));return gains[0]||null}
function sameSpeciesDonors(target,mutant=false){return state.pets.filter(p=>p.id!==target.id&&samePetSpecies(p,target)&&!p.locked&&p.id!==state.activePetId&&!!p.mutant===!!mutant)}
function fusionPlan(target){if(!target)return null;const donors=sameSpeciesDonors(target,false);if(!donors.length)return null;const plans=donors.map(donor=>{const apt=bestAptitudeInheritance(target,donor),evo=petEvolutionValue(donor);return{target,donor,apt,evo,keep:petKeepScore(donor)}}).filter(x=>x.evo>0||x.apt);if(!plans.length)return null;plans.sort((a,b)=>Number(!!b.apt)-Number(!!a.apt)||(b.apt?.gap||0)-(a.apt?.gap||0)||a.keep-b.keep);const best=plans[0];best.cost=Math.round(80+(target.tier||1)*55+(best.donor.tier||1)*25+Math.pow(1.10,Math.max(0,(target.tier||1)-1))*35+(best.apt?.gap||0)*45);return best}
function mutantFusionPlan(target){if(!target)return null;const donors=sameSpeciesDonors(target,true);if(!donors.length)return null;const plans=donors.map(donor=>({target,donor,apt:bestAptitudeInheritance(target,donor),evo:petEvolutionValue(donor),keep:petKeepScore(donor)})).filter(x=>x.evo>0||x.apt);if(!plans.length)return null;plans.sort((a,b)=>a.keep-b.keep||(b.apt?.gap||0)-(a.apt?.gap||0));const best=plans[0];best.cost=Math.round(160+(target.tier||1)*80+(best.donor.tier||1)*40+Math.pow(1.10,Math.max(0,(target.tier||1)-1))*55);return best}
function fusionPreviewText(plan){return plan.apt?`资质继承：${PET_APT_NAMES[plan.apt.stat]} ${plan.apt.from} → ${plan.apt.to}\n`:''}
function mergePet(id){const target=state.pets.find(x=>x.id===id);if(!target)return alert('找不到融合目标。');const plan=fusionPlan(target);if(!plan){const ordinary=sameSpeciesDonors(target,false);if(!ordinary.length)return alert('没有可用的普通同类素材。融合进阶只要求同物种；若素材任一资质更高，会自动继承差距最大的一项。');return alert('当前普通同类素材既不能提供有效进阶经验，也没有可继承的更高资质。')}if(state.gold<plan.cost)return alert(`金币不足，需要${plan.cost}金币。`);const beforeTier=target.tier||1,beforeLevel=target.level||1,levelXp=petLevelInvestment(plan.donor);if(!confirm(`同类融合预览：\n目标：${beforeTier}阶 Lv.${beforeLevel} ${PET_TYPES[target.type].name} ${target.name}\n素材：${plan.donor.tier||1}阶 Lv.${plan.donor.level||1} ${PET_TYPES[plan.donor.type].name} ${plan.donor.name}\n继承进阶经验：+${plan.evo}（包含素材历次融合已经消耗的经验）\n继承等级经验：+${levelXp}\n${fusionPreviewText(plan)}消耗：${plan.cost}金币\n\n素材已有的阶级经验、等级经验和更高资质都会保留；素材会永久消失。`))return;state.gold-=plan.cost;if(plan.apt)migratePetAptitudes(target)[plan.apt.stat]=plan.apt.to;const inherited=inheritPetEvolution(target,plan.donor),upgrades=inherited.upgrades;removePet(plan.donor.id);const ps=petStats(target);target.hp=Math.min(ps.maxHp,Math.max(1,target.hp||ps.maxHp));const tierLog=upgrades.length?`，进化至${target.tier}阶`:'',levelLog=target.level>beforeLevel?`，Lv.${beforeLevel}→Lv.${target.level}`:'';log(`融合完成：进阶经验+${inherited.evolutionXp}，等级经验+${inherited.levelXp}${plan.apt?`，${PET_APT_NAMES[plan.apt.stat]}提升至${plan.apt.to}`:''}${tierLog}${levelLog}。`,'loot');render()}
function mergeMutantPet(id){const target=state.pets.find(x=>x.id===id);if(!target)return alert('找不到融合目标。');const plan=mutantFusionPlan(target);if(!plan)return alert('没有可消耗的变异X同类素材。出战宠物和锁定宠物不会被自动选作素材。');if(state.gold<plan.cost)return alert(`金币不足，需要${plan.cost}金币。`);const donor=plan.donor,beforeLevel=target.level||1,warning=target.mutant?'目标本身已经是变异X。':'注意：素材的“变异X”不会转移给普通目标，但其全部阶级与等级培养成果会保留。';if(!confirm(`【变异X进阶】\n目标：${target.tier||1}阶 Lv.${beforeLevel} ${target.mutant?'变异X ':''}${target.name}\n素材：${donor.tier||1}阶 Lv.${donor.level||1} 变异X ${donor.name}\n继承进阶经验：+${plan.evo}\n继承等级经验：+${petLevelInvestment(donor)}\n${plan.apt?`额外继承：${PET_APT_NAMES[plan.apt.stat]} ${plan.apt.from} → ${plan.apt.to}\n`:''}消耗：${plan.cost}金币\n\n${warning}\n\n素材极其稀有且会永久消失，确定继续？`))return;if(!confirm('再次确认：永久消耗这只变异X宠物作为进阶素材？'))return;state.gold-=plan.cost;if(plan.apt)migratePetAptitudes(target)[plan.apt.stat]=plan.apt.to;const inherited=inheritPetEvolution(target,donor),upgrades=inherited.upgrades;removePet(donor.id);const ps=petStats(target);target.hp=Math.min(ps.maxHp,Math.max(1,target.hp||ps.maxHp));log(`变异融合完成：进阶经验+${inherited.evolutionXp}，等级经验+${inherited.levelXp}${upgrades.length?`，连续进化至${target.tier}阶`:''}${target.level>beforeLevel?`，Lv.${beforeLevel}→Lv.${target.level}`:''}。`,'loot');render()}
function togglePetLock(id){const p=state.pets.find(x=>x.id===id);if(!p)return;p.locked=!p.locked;render()}
function shouldAutoProcessPet(p){const f=state.petFilter||{minGrade:'F',minTier:1,action:'release',keepAnyS:true};if(p.mutant)return false;const belowTier=(p.tier||1)<Number(f.minTier||1),belowGrade=gradeIndex(petOverallGrade(p))<gradeIndex(f.minGrade||'F');if(!belowTier&&!belowGrade)return false;if(f.keepAnyS&&petHasHighAptitude(p,'S'))return false;return true}
function receivePet(p){const grade=petOverallGrade(p),filter=state.petFilter||{minGrade:'F',minTier:1,action:'release',keepAnyS:true};if(shouldAutoProcessPet(p)){if(filter.action==='feed'&&activePet()){const xp=16+petOverallScore(p)*8+(p.tier||1)*8;petGainXp(activePet(),xp);log(`自动筛选：${p.name}[${grade}]未达保留阈值，作为素材转化为${xp}宠物经验。`,'loot')}else{const value=petDustValue(p);state.petDust+=value;log(`自动筛选：${p.name}[${grade}]未达保留阈值，放归获得${value}灵宠精华。`,'loot')}return false}if(state.pets.length>=state.petCapacity){const candidates=state.pets.filter(x=>x.id!==state.activePetId&&!x.locked&&!x.mutant).sort((a,b)=>petKeepScore(a)-petKeepScore(b)),worst=candidates[0];if(worst&&petKeepScore(p)>petKeepScore(worst)){const value=petDustValue(worst);removePet(worst.id);state.petDust+=value;state.pets.push(p);log(`宠物仓已满，放归较弱的${worst.name}并保留${p.mutant?'红色变异X ':''}${p.name}。`,'loot')}else if(p.mutant){state.pets.push(p);state.petCapacity+=1;log(`获得红色变异X宠物：仓库临时扩展1格以避免自动丢失。`,'sys')}else{const value=petDustValue(p);state.petDust+=value;log(`宠物仓已满，${p.name}[${grade}]自动放归，灵宠精华+${value}。`,'loot');return false}}else state.pets.push(p);if(!state.activePetId)state.activePetId=p.id;log(`区域首领掉落宠物：${p.tier||1}阶 ${p.mutant?'<span class="mutant-x">变异 X</span> ':''}${p.name}（${PET_TYPES[p.type].name}）｜综合<span class="grade-${grade}">${grade}</span>｜${aptitudeText(p)}。`,'loot');return true}
const PET_LEVEL_MAX=100;
function petXpNeed(level){return Math.round(20+2.5*Math.pow(Math.max(1,level),2))}
function petGainXp(p,n){if((p.level||1)>=PET_LEVEL_MAX){p.level=PET_LEVEL_MAX;p.xp=0;return}n=Math.max(1,Math.round(n*rebirthProfile().petXp));p.xp+=n;while(p.level<PET_LEVEL_MAX&&p.xp>=petXpNeed(p.level)){p.xp-=petXpNeed(p.level);p.level++;p.hp=petStats(p).maxHp}if(p.level>=PET_LEVEL_MAX){p.level=PET_LEVEL_MAX;p.xp=0}}
