function petSpeciesSpecial(p,e,ps,s){
 if(!p||!e)return;const n=p.battleTurns||0,dm=petSpeciesDamageMult(p,e),skill=petTierInstincts(p).speciesSkill*(1+amuletPowers().petSpecies)*petExclusiveSkillScale(p);
 if(p.name==='灰尾幼狼'&&n%5===0){const dmg=Math.max(1,Math.round(ps.atk*1.45*dm*skill-enemyDefenseAgainstCompanion(e)*.25));e.hp-=dmg;healFromGlobalLifesteal(dmg,p.name);e.petArmorBreakTurns=Math.max(e.petArmorBreakTurns||0,2);e.petArmorBreakPower=Math.min(.55,.22*petExclusiveSkillScale(p));log(`${p.name}发动【月影扑杀】，造成${dmg}伤害并撕开防御。`,'skill')}
 if(p.name==='裂风幼狮'&&n%5===0){const dmg=Math.max(1,Math.round(ps.atk*.82*dm*skill-enemyDefenseAgainstCompanion(e)*.20));e.hp-=dmg;healFromGlobalLifesteal(dmg,p.name);e.speciesWeakenTurns=2;e.speciesWeakenPower=Math.min(.48,.20*petExclusiveSkillScale(p));log(`${p.name}发动【裂风咆哮】，造成${dmg}伤害并压制敌人攻击。`,'skill')}
 if(p.name==='树灵幼芽'&&n%4===0){const ph=Math.max(2,Math.round((s.maxHp*.06+ps.magic*.35)*skill)),self=Math.max(2,Math.round((ps.maxHp*.08+ps.magic*.28)*skill));if(state.hp>0)state.hp=Math.min(s.maxHp,state.hp+ph);p.hp=Math.min(ps.maxHp,p.hp+self);log(`${p.name}发动【萌芽回春】，玩家恢复${state.hp>0?ph:0}，自身恢复${self}生命。`,'skill')}
 if(p.name==='霜鳍幼兽'&&n%4===0){const dmg=Math.max(1,Math.round((ps.magic*1.05+ps.atk*.32)*dm*skill-enemyDefenseAgainstCompanion(e)*.24));e.hp-=dmg;healFromGlobalLifesteal(dmg,p.name);e.frostbiteTurns=2;e.frostbitePower=Math.min(.35,.10*petExclusiveSkillScale(p));log(`${p.name}发动【寒霜吐息】，造成${dmg}伤害并削弱敌人攻势。`,'skill')}
 if(p.name==='王魂侍从'&&n%5===0){state.temp.speciesGuardTurns=2;state.temp.speciesGuardPower=Math.min(.50,.20*petExclusiveSkillScale(p));log(`${p.name}发动【王魂庇护】，玩家接下来2次受击获得额外减伤。`,'skill')}
 if(p.name==='星核幼龙'&&n%4===0){const raw=(Math.max(ps.atk,ps.magic)*1.65*dm+Math.min(ps.atk,ps.magic)*.35)*skill,dmg=Math.max(1,Math.round(raw-e.def*.40));e.hp-=dmg;healFromGlobalLifesteal(dmg,p.name);log(`${p.name}发动【星核吐息】，造成${dmg}穿透伤害。`,'skill')}
}
function petTierMult(tier){return 1+PET_TIER_GROWTH_STEP*Math.max(0,Math.round(tier||1)-1)}
function petTierInstincts(p){const t=Math.max(1,Math.round(p?.tier||1)),k=petInstinctScale(p),b={hp:1,atk:1,def:1,magic:1,damage:1,speciesSkill:1,damageTaken:1,bossDamage:1,regen:0,all:1};if(t>=1)b.hp*=1+.05*k;if(t>=2){if(p?.type==='Attack')b.atk*=1+.05*k;else if(p?.type==='Magic')b.magic*=1+.05*k;else if(p?.type==='Defense')b.def*=1+.05*k;else{b.atk*=1+.03*k;b.magic*=1+.03*k}}if(t>=3)b.def*=1+.05*k;if(t>=4)b.speciesSkill*=1+.05*k;if(t>=5)b.damage*=1+.05*k;if(t>=6)b.speciesSkill*=1+.10*k;if(t>=7)b.damageTaken*=1-Math.min(.35,.06*k);if(t>=8)b.bossDamage*=1+.08*k;if(t>=9)b.regen+=.015*k;if(t>=10)b.all*=1+.08*k;return b}
function petTierInstinctText(p){const t=Math.max(1,Math.round(p?.tier||1));const unlocked=Object.entries(PET_TIER_INSTINCTS).filter(([tier])=>t>=Number(tier)).map(([tier,x])=>`${tier}阶【${x.name}】${x.desc}`);const next=Object.entries(PET_TIER_INSTINCTS).find(([tier])=>Number(tier)>t);return `${unlocked.join('｜')}${next?`｜下一特性：${next[0]}阶【${next[1].name}】`:'｜10阶后只继续固定+12%基础全域倍率，不再新增机制。'}`}
function petEvolutionSameTierCount(tier){return Math.max(10,Math.round(10*Math.pow(1.25,Math.max(0,Math.round(tier||1)-1))))}
function petEvolutionNeed(p){const t=Math.max(1,Math.round(p?.tier||1));return t*petEvolutionSameTierCount(t)}
function petEvolutionValue(donor){const tier=Math.max(1,Math.round(donor?.tier||1));return tier*(donor?.mutant?100:1)}
function petEvolutionProgress(p){return clamp((p?.evolutionXp||0)/Math.max(1,petEvolutionNeed(p)),0,1)}
function petEvolutionText(p){const t=Math.max(1,Math.round(p?.tier||1)),need=petEvolutionNeed(p),xp=Math.max(0,Math.round(p?.evolutionXp||0));return `进阶经验 ${xp}/${need}｜${t}→${t+1}阶约需${petEvolutionSameTierCount(t)}只同阶普通宠物｜基础全域倍率×${petTierMult(t).toFixed(2)} → ×${petTierMult(t+1).toFixed(2)}`}
function applyPetEvolutionXp(p,amount){if(!p||amount<=0)return[];p.evolutionXp=Math.max(0,Math.round(p.evolutionXp||0))+Math.round(amount);const upgrades=[];let guard=0;while(guard++<1000){const need=petEvolutionNeed(p);if(p.evolutionXp<need)break;p.evolutionXp-=need;const from=Math.max(1,Math.round(p.tier||1));p.tier=from+1;upgrades.push([from,p.tier])}return upgrades}
function rollPetTier(mapDef=map()){return Math.min(6,mapDef.petTier||1)}
const PET_GRADES=['F','E','D','C','B','A','S','SS','SSS'];
const PET_GRADE_MULT={F:.72,E:.82,D:.91,C:1,B:1.10,A:1.22,S:1.36,SS:1.52,SSS:1.72};
const PET_X_EQUIV_MULT=2.20;
const PET_MUTANT_MULT=PET_X_EQUIV_MULT/PET_GRADE_MULT.SSS;
const PET_GRADE_WEIGHTS=[5,10,18,26,20,12,6,2.5,.5];
const PET_APT_NAMES={hp:'体魄',atk:'力量',def:'守护',magic:'灵性'};
const PET_DUST_VALUES={F:1,E:2,D:3,C:4,B:6,A:9,S:14,SS:22,SSS:35};
function gradeIndex(g){const i=PET_GRADES.indexOf(g);return i<0?3:i}
function gradeFromIndex(i){return PET_GRADES[clamp(Math.round(i),0,PET_GRADES.length-1)]}
function rollPetGrade(mapIndex=0){const weights=PET_GRADE_WEIGHTS.slice(),boost=Math.max(0,mapIndex*.16+stats().luck*.003);let total=weights.reduce((a,b)=>a+b,0),r=Math.random()*total,idx=0;for(;idx<weights.length;idx++){r-=weights[idx];if(r<=0)break}while(idx<8&&Math.random()<boost)idx++;return gradeFromIndex(idx)}
function rollPetAptitudes(type,mapIndex){const apt={hp:rollPetGrade(mapIndex),atk:rollPetGrade(mapIndex),def:rollPetGrade(mapIndex),magic:rollPetGrade(mapIndex)};if(type==='Attack')apt.atk=gradeFromIndex(gradeIndex(apt.atk)+1);if(type==='Defense'){apt.hp=gradeFromIndex(gradeIndex(apt.hp)+1);apt.def=gradeFromIndex(gradeIndex(apt.def)+1)}if(type==='Magic')apt.magic=gradeFromIndex(gradeIndex(apt.magic)+1);return apt}
function migratePetAptitudes(p){if(p.aptitudes)return p.aptitudes;const q=Number(p.quality||1),base=clamp(Math.round((q-.82)/.045),0,8);p.aptitudes={hp:gradeFromIndex(base),atk:gradeFromIndex(base),def:gradeFromIndex(base),magic:gradeFromIndex(base)};if(p.type==='Attack')p.aptitudes.atk=gradeFromIndex(base+1);if(p.type==='Defense'){p.aptitudes.hp=gradeFromIndex(base+1);p.aptitudes.def=gradeFromIndex(base+1)}if(p.type==='Magic')p.aptitudes.magic=gradeFromIndex(base+1);delete p.quality;return p.aptitudes}
function petOverallScore(p){const a=migratePetAptitudes(p);return Math.round((gradeIndex(a.hp)+gradeIndex(a.atk)+gradeIndex(a.def)+gradeIndex(a.magic))/4)}
function petOverallGrade(p){return gradeFromIndex(petOverallScore(p))}
function petHasHighAptitude(p,min='S'){const a=migratePetAptitudes(p),n=gradeIndex(min);return Object.values(a).some(g=>gradeIndex(g)>=n)}
function aptitudeText(p){const a=migratePetAptitudes(p);return Object.entries(a).map(([k,g])=>`${PET_APT_NAMES[k]}<span class="grade-${g}">${g}</span>`).join(' / ')}
function fresh(){return {version:VERSION,started:false,race:null,style:null,name:'旅者',nextRace:null,nextStyle:null,unlockedRaces:[],unlockedClasses:[],identityPity:0,firstBossMilestoneClaimed:false,starterProfessionPending:false,level:1,xp:0,gold:20,age:16,rebirths:0,soul:0,rebirthLaws:{war:0,time:0,hunt:0},pendingRebirthLaw:'war',base:{str:6,int:6,dex:6,will:6,luck:6},growthCarry:{str:0,int:0,dex:0,will:0,luck:0},hp:1,mp:1,equipment:{weapon:null,head:null,armor:null,boots:null,ring:null,amulet:null},inventory:[],autoSell:0,gearScorePrefs:null,skills:{},skillUse:{},skillMastered:{},skillPriority:{attack:[],defense:[]},skillReadyAt:{},specialSkillsUnlocked:[],combatTurn:0,activeSkills:[],activeSkillSlots:[],passiveSkillSlots:[],mapId:'meadow',enemy:null,bossProgress:{},bossCycles:{},killsByMap:{},totalKills:0,totalWins:0,totalLosses:0,highRiskWins:0,pets:[],activePetId:null,nextId:1,nextItemId:1,petDust:0,petCapacity:12,inventoryCapacity:40,titlesUnlocked:[],equippedTitle:null,log:[],logFilters:{damage:false,defense:false,loot:true,important:true,system:true},lastSave:Date.now(),running:true,tab:'character',metrics:{startedAt:Date.now(),xp:0,gold:0,drops:0,battles:0,wins:0,losses:0,byMap:{}},petFilter:{minGrade:'F',minTier:1,action:'release',keepAnyS:true},shop:{gearBuys:0,petTraining:0,inventoryUpgrades:0,petUpgrades:0}}}
let state=fresh();let tickTimer=null,saveTimer=null;
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function rnd(a,b){return Math.floor(Math.random()*(b-a+1))+a}
function pickWeighted(arr){const total=arr.reduce((n,x)=>n+x.w,0);let r=Math.random()*total;for(const x of arr){r-=x.w;if(r<=0)return x}return arr[arr.length-1]}
function inferLogCategory(msg,cls=''){if(cls==='important')return'important';if(/神话|永久解锁|技能传承|被动传承|变异 X|变异X|极稀有|身份/.test(msg))return'important';if(cls==='loot')return'loot';if(cls==='lose')return'defense';if(cls==='skill')return /恢复|减轻|护|治疗|吸收|防御|衰弱|守护|镜返/.test(msg)?'defense':'damage';if(cls==='sys'||cls==='win')return'system';return'damage'}
function log(msg,cls='',category=null){const cat=category||inferLogCategory(msg,cls);state.log.unshift({msg,cls,category:cat,t:Date.now()});state.log=state.log.slice(0,180);renderLogOnly()}
function ensureLogFilters(){state.logFilters={damage:false,defense:false,loot:true,important:true,system:true,...(state.logFilters||{})};return state.logFilters}
function filteredLogs(){const f=ensureLogFilters();return (state.log||[]).filter(x=>f[x.category||inferLogCategory(x.msg,x.cls)]!==false)}
function toggleLogFilter(k){const f=ensureLogFilters();f[k]=!f[k];save();renderLogOnly()}
function setImportantLogMode(){state.logFilters={damage:false,defense:false,loot:false,important:true,system:false};save();renderLogOnly()}
function setAllLogMode(){state.logFilters={damage:true,defense:true,loot:true,important:true,system:true};save();renderLogOnly()}
function renderLogControls(){const f=ensureLogFilters(),labels={damage:'伤害',defense:'防御/治疗',loot:'掉落',important:'重要',system:'系统'};return `<div class="log-toolbar"><b>战斗日志</b><div class="log-filter-row">${Object.entries(labels).map(([k,n])=>`<button class="${f[k]?'active':''}" onclick="toggleLogFilter('${k}')">${n}</button>`).join('')}<button onclick="setImportantLogMode()">只看重要</button><button onclick="setAllLogMode()">全部</button></div></div>`}
