function renderLogOnly(){const dock=document.getElementById('log-dock');if(!dock)return;dock.innerHTML=renderLogControls()+`<div class="log-stream">${filteredLogs().map(x=>`<div class="${x.cls} cat-${x.category||inferLogCategory(x.msg,x.cls)}">${x.msg}</div>`).join('')||'<div class="muted">当前筛选没有日志。</div>'}</div>`}
function map(){return MAPS.find(x=>x.id===state.mapId)}
function titleMods(){return state.equippedTitle?TITLES[state.equippedTitle].mods:{}}
function equippedBonuses(){const b={str:0,int:0,dex:0,will:0,luck:0,hp:0,mp:0,crit:0,def:0,atk:0};Object.values(state.equipment).filter(Boolean).forEach(it=>{const mult=1+(it.refine||0)*.08;Object.entries(it.stats).forEach(([k,v])=>b[k]=(b[k]||0)+Math.round(v*mult))});return b}
function weaponProfile(){const w=state.equipment.weapon;return w&&w.weaponType?WEAPON_TYPES[w.weaponType]:null}
function ensureMetric(id=state.mapId){state.metrics=state.metrics||{startedAt:Date.now(),xp:0,gold:0,drops:0,battles:0,wins:0,losses:0,byMap:{}};state.metrics.byMap=state.metrics.byMap||{};state.metrics.byMap[id]=state.metrics.byMap[id]||{startedAt:Date.now(),xp:0,gold:0,drops:0,battles:0,wins:0,losses:0};return state.metrics.byMap[id]}
function metricRate(metric,key){const mins=Math.max(1/60,(Date.now()-(metric.startedAt||Date.now()))/60000);return (metric[key]||0)/mins}
function prepareNewBattle(){const s=stats();state.hp=s.maxHp;state.mp=s.maxMp;state.temp={petGuardTurns:0,petAtkBuffTurns:0,petAtkBuff:0,speciesGuardTurns:0,speciesGuardPower:0,playerFallenLogged:false};const p=activePet();if(p){const ps=petStats(p);p.hp=ps.maxHp;p.battleTurns=0;p.fallen=false}}
function expectedDamage(s=stats()){const critMult=s.critMult||1.7;return s.atk*(s.balance/100+(1-s.balance/100)*.5)*(1+(s.crit/100)*(critMult-1))}
function representativeEnemy(mapDef){const region=Math.max(1,mapDef.cp/MAPS[0].cp),lv=Math.round((mapDef.levels[0]+mapDef.levels[1])/2);return{level:lv,maxHp:Math.round((72+lv*11)*Math.pow(region,.65)),atk:Math.round((11+lv*1.45)*Math.pow(region,.33)),def:Math.round((2.5+lv*.50)*Math.pow(region,.22)),speed:Math.round((7+lv*.42)*Math.pow(region,.07)),boss:false,hp:1}}
function expectedPetRoundDamageAgainst(e){const p=activePet();if(!p)return 0;const ps=petStats(p),m=petSpeciesDamageMult(p,{...e,hp:e.maxHp});let d=0;if(p.type==='Attack')d=Math.max(1,ps.atk*1.25*m+ps.magic*.22-e.def*.38);else if(p.type==='Defense')d=Math.max(1,ps.atk*.66*m+ps.def*.18-e.def*.30);else if(p.type==='Magic')d=Math.max(1,(ps.magic*.79*m+ps.atk*.19)-e.def*.22);else d=Math.max(1,(ps.atk*.78+ps.magic*.58)*m-e.def*.34);const sp=petSpeciesData(p);if(sp?.skill&&p.name==='星核幼龙')d+=Math.max(ps.atk,ps.magic)*1.65*m/4;else if(p.name==='灰尾幼狼')d+=ps.atk*1.45*m/5;else if(p.name==='裂风幼狮')d+=ps.atk*.82*m/5;else if(p.name==='霜鳍幼兽')d+=(ps.magic*1.05+ps.atk*.32)*m/4;return Math.max(0,d)}
function expectedDefenseFactor(s=stats()){let incoming=1,healEhp=0;const ids=(state.activeSkillSlots||[]).filter(id=>SKILLS[id]?.type==='active'&&SKILLS[id].cat==='defense'&&skillUsable(id));let remain=1;for(const id of ids){const sk=SKILLS[id],chance=skillTriggerChance(id,s)/(1+skillTriggerChance(id,s)*(sk.cooldown||0)*.65),use=remain*chance,p=skillPower(id);if(sk.kind==='reduce'||sk.kind==='mirror')incoming*=1-use*Math.min(.80,(sk.reduce||.45)*p)*.55;else if(sk.kind==='heal')healEhp+=use*(s.maxHp*(sk.healPct||.23)+s.int*(sk.intScale||.8))*p*.35;remain*=1-chance;if(remain<.08)break}return{incoming:clamp(incoming,.55,1),healEhp}}
function estimatedWin(mapDef){const s=stats(),e=representativeEnemy(mapDef),skillFactor=expectedAttackSkillFactor(s),playerHit=Math.max(1,expectedDamage(s)*skillFactor-e.def*.68),petHit=expectedPetRoundDamageAgainst(e),out=Math.max(1,playerHit+petHit),defx=expectedDefenseFactor(s),p=activePet();let incoming=Math.max(1,e.atk-s.def*.65)*defx.incoming;if(p&&petAlive(p)){const target=({Attack:.22,Defense:.42,Magic:.28,Balance:.26}[p.type]||.25);incoming*=1-target*.75;if(p.type==='Defense')incoming*=.82;if(p.type==='Magic')defx.healEhp+=petStats(p).magic*.30}const ttk=e.maxHp/out,ttd=(s.maxHp+defx.healEhp)/Math.max(1,incoming),speedAdj=s.speed>=e.speed?1.08:.92,ratio=(ttd/Math.max(.25,ttk))*speedAdj;return clamp(Math.round(50+36*Math.log2(Math.max(.12,ratio))),2,98)}
function ensureIdentityState(){state.unlockedRaces=Array.isArray(state.unlockedRaces)?state.unlockedRaces.filter(id=>RACES[id]):[];state.unlockedClasses=Array.isArray(state.unlockedClasses)?state.unlockedClasses.filter(id=>STYLES[id]):[];if(state.race&&RACES[state.race]&&!state.unlockedRaces.includes(state.race))state.unlockedRaces.push(state.race);if(state.style&&STYLES[state.style]&&!state.unlockedClasses.includes(state.style))state.unlockedClasses.push(state.style);state.identityPity=Math.max(0,Number(state.identityPity||0))}
function switchRace(id){ensureIdentityState();if(!state.unlockedRaces.includes(id)||!RACES[id])return;if(id===state.race)return;const old=RACES[state.race]?.name||'未知';state.race=id;state.enemy=null;prepareNewBattle();save();render();log(`种族切换：${old} → ${RACES[id].name}。种族特性随当前种族变化，不会被传承。`,'important','important')}
function switchClass(id){ensureIdentityState();if(!state.unlockedClasses.includes(id)||!STYLES[id])return;if(id===state.style)return;const old=STYLES[state.style]?.name||'未知';state.style=id;state.enemy=null;state.skillReadyAt={};syncSkills();prepareNewBattle();save();render();log(`职业切换：${old} → ${STYLES[id].name}。未满Lv.10的旧职业技能暂时不可用，已传承技能继续可用。`,'important','important')}
function identityMaxRarityForMap(m=map()){return [1,2,3,3,4,5][Math.max(0,MAPS.indexOf(m))]??1}
function rollIdentityRarity(maxR){const w=[42,27,16,9,4.5,1.5],pool=[];for(let r=0;r<=maxR;r++)pool.push({r,w:w[r]});return pickWeighted(pool).r}
function identityDropChance(){const luck=stats().luck,hunt=rebirthProfile().special||1,pity=Math.min(.10,(state.identityPity||0)*.004);return clamp((.052+Math.min(.025,luck/6000))*hunt+pity,.035,.18)}
function identityDuplicateReward(rarity){return Math.round(90*Math.pow(rarity+1,1.65))}
function tryDropIdentity(e,m){if(!e?.boss)return false;ensureIdentityState();if(Math.random()>=identityDropChance()){state.identityPity=(state.identityPity||0)+1;return false}const maxR=identityMaxRarityForMap(m),rarity=rollIdentityRarity(maxR),racePool=Object.keys(RACES).filter(id=>RACES[id].rarity===rarity),classPool=Object.keys(STYLES).filter(id=>STYLES[id].rarity===rarity);let kind=Math.random()<.50?'race':'class',pool=kind==='race'?racePool:classPool,unlocked=kind==='race'?state.unlockedRaces:state.unlockedClasses;if(!pool.length){kind=kind==='race'?'class':'race';pool=kind==='race'?racePool:classPool;unlocked=kind==='race'?state.unlockedRaces:state.unlockedClasses}if(!pool.length){state.identityPity++;return false}const locked=pool.filter(id=>!unlocked.includes(id)),chosenPool=(locked.length&&Math.random()<.85)?locked:pool,id=chosenPool[rnd(0,chosenPool.length-1)],def=kind==='race'?RACES[id]:STYLES[id],r=RARITIES[def.rarity];if(!unlocked.includes(id)){unlocked.push(id);state.identityPity=0;log(`【身份掉落】${r.name}${kind==='race'?'种族':'职业'}【${def.name}】永久解锁！`,'important','important')}else{const reward=identityDuplicateReward(def.rarity);state.gold+=reward;state.identityPity=Math.max(0,(state.identityPity||0)-2);log(`Boss再次掉落已解锁的${r.name}${kind==='race'?'种族':'职业'}【${def.name}】，转化为${reward}金币。`,'loot','loot')}return true}
const REBIRTH_LAW_MAX=3;
const REBIRTH_LAWS={war:{name:'破军法则',desc:'强化战斗。每级：玩家最终攻击+10%，宠物攻击/魔力+8%。最高Lv.3。'},time:{name:'时流法则',desc:'强化周回。每级：经验+12%、技能熟练+15%、宠物经验+12%；Boss所需普通怪数量显著降低。最高Lv.3。'},hunt:{name:'猎命法则',desc:'强化收获。每级：装备/宠物掉落+8%，神话概率+6%，变异X概率+5%，特殊技能书+5%。最高Lv.3。'}};
function ensureRebirthLaws(){state.rebirthLaws={war:0,time:0,hunt:0,...(state.rebirthLaws||{})};if(!REBIRTH_LAWS[state.pendingRebirthLaw])state.pendingRebirthLaw='war';return state.rebirthLaws}
function rebirthProfile(){const r=Math.max(0,state.rebirths||0),laws=ensureRebirthLaws(),damage=(1+.08*r)*(1+.10*Math.min(REBIRTH_LAW_MAX,laws.war||0)),hp=1,def=1,petPower=(1+.08*r)*(1+.08*Math.min(REBIRTH_LAW_MAX,laws.war||0)),xp=(1+.25*r)*(1+.12*Math.min(REBIRTH_LAW_MAX,laws.time||0)),skillMastery=(1+.20*r)*(1+.15*Math.min(REBIRTH_LAW_MAX,laws.time||0)),petXp=(1+.20*r)*(1+.12*Math.min(REBIRTH_LAW_MAX,laws.time||0)),gold=1,bossCycle=1,hunt=Math.min(REBIRTH_LAW_MAX,laws.hunt||0),gearDrop=1+.08*hunt,petDrop=1+.08*hunt,mythic=1+.06*hunt,mutation=1+.05*hunt,special=1+.05*hunt;return{r,damage,hp,def,petPower,xp,skillMastery,petXp,gold,bossCycle,gearDrop,petDrop,mythic,mutation,special}}
function rebirthUnlockText(){return (state.rebirths||0)>0?'你已经经历过轮回：后续周目会更快，但所有地图始终都可自由进入。':'尚未转生：所有地图仍可进入；高阶地图不会拦你，只会用实际战斗强度把你击败。'}
function effectiveCritChance(raw){raw=Math.max(0,Number(raw)||0);if(raw<=25)return raw;if(raw<=100)return 25+(raw-25)*(50/75);if(raw<=200)return 75+(raw-100)*.10;if(raw<=500)return 85+(raw-200)/30;return 100-2500/raw}
function critCurveText(raw){const actual=effectiveCritChance(raw);return `原始暴击 ${raw.toFixed(1)} → 实际暴击率 ${actual.toFixed(1)}%`}
