function stats(){
 const b=equippedBonuses(),tm=titleMods(),wp=weaponProfile(),wm=wp?.mods||{},sm=skillMasteryTotals(),psv=passiveSkillTotals(),rp=rebirthProfile(),rt=raceTraitPowers(),ib=identityBaseAttributes();
 let str=ib.str+b.str,int=ib.int+b.int,dex=ib.dex+b.dex,will=ib.will+b.will,luck=ib.luck+b.luck;const all=tm.all||1;str*=all;int*=all;dex*=all;will*=all;luck*=all;
 let maxHp=Math.round((55+state.level*8+str*5+will*3+b.hp)*(rt.hp||1)*(1+sm.hpPct+psv.hpPct)*rp.hp),maxMp=Math.round((25+state.level*3+int*5+will*2+b.mp+(wm.mp||0))*(1+sm.mpPct+psv.mpPct));const a=classArchetype();let baseAtk;if(a==='melee')baseAtk=str*2.35+dex*.30+state.level*2;else if(a==='ranged')baseAtk=dex*2.25+str*.35+state.level*2;else baseAtk=int*2.25+will*.25+state.level*1.9;let atk=Math.round((baseAtk+(b.atk||0))*(1+sm.atkPct+psv.atkPct)*rp.damage*(rt.damage||1));if(a==='ranged')atk*=wm.rangedMult||1;if(a==='magic')atk*=wm.magicMult||1;atk*=wm.atkMult||1;let def=Math.round((will*1.35+str*.32+state.level*.7+(b.def||0))*(1+sm.defPct+psv.defPct)*rp.def*(rt.def||1)),rawCrit=Math.max(0,5+dex*.32+luck*.24+(b.crit||0)+(wm.crit||0)+sm.crit+psv.crit),crit=applyAmuletCritEfficiency(effectiveCritChance(rawCrit)),balance=clamp(67+dex*.45+(wm.balance||0),55,98),speed=Math.round((10+dex*.75+(wm.speed||0))*(1+sm.speedPct+psv.speedPct)*(rt.speed||1)),critMult=1.7+(wm.critMult||0)+sm.critDmg+psv.critDmg,skillChance=(wm.skillChance||0)+sm.skillChance+psv.skillChance+amuletPowers().skillChance+(rt.skillChance||0);atk=Math.round(atk*(tm.atk||1));return{str:Math.round(str),int:Math.round(int),dex:Math.round(dex),will:Math.round(will),luck:Math.round(luck),maxHp,maxMp,atk,def,rawCrit,crit,balance,speed,critMult,skillChance}
}
function expectedAttackSkillFactor(s=stats()){const ordered=(state.activeSkillSlots||[]).filter(id=>SKILLS[id]?.type==='active'&&SKILLS[id].cat==='attack'&&skillUsable(id));let remaining=1,factor=1;for(const id of ordered){const sk=SKILLS[id],chance=skillTriggerChance(id,s),availability=chance/(1+chance*(sk.cooldown||0)*.65);let use=remaining*availability,eff=(sk.mult||1)*(sk.hits||1)*skillPower(id);if(sk.kind==='execute')use*=.25;const ignore=clamp((sk.ignore||0)+(skillLevel(id)-1)*(sk.ignoreGrowth||0),0,.9);eff*=1+ignore*.25;factor+=use*Math.max(0,eff-1);remaining*=1-availability;if(remaining<.05)break}return clamp(factor,1,3.2)}
function cp(){const s=stats(),p=activePet(),ps=p?petStats(p):null,ehp=s.maxHp*(1+s.def/75),dps=expectedDamage(s)*expectedAttackSkillFactor(s)*(1+s.speed/55),sustain=s.maxMp*.12+s.will*.55;let petValue=0;if(ps&&p){if(p.type==='Attack')petValue=ps.atk*1.55+ps.maxHp*.05;else if(p.type==='Defense')petValue=ps.maxHp*.16+ps.def*1.35+ps.atk*.45;else if(p.type==='Magic')petValue=ps.magic*1.55+ps.maxHp*.10+ps.def*.45;else petValue=ps.atk*.95+ps.magic*.9+ps.maxHp*.10+ps.def*.6}return Math.round(ehp*.34+dps*2.15+sustain+petValue)}
function xpNeed(l=state.level){return Math.round(30+l*l*6.3)}
function growthShares(raceId=state.race,styleId=state.style){const r=RACES[raceId]?.growth||RACES.human.growth,c=STYLES[styleId]?.growth||STYLES.melee.growth,keys=['str','int','dex','will','luck'],raw={};let sum=0;keys.forEach(k=>{raw[k]=r[k]*c[k];sum+=raw[k]});const out={};keys.forEach(k=>out[k]=raw[k]/sum);return out}
function identityBaseAttributes(){const race=RACES[state.race]||RACES.human,job=STYLES[state.style]||STYLES.melee,base=6+Math.max(0,state.level-1)*.60,out={};['str','int','dex','will','luck'].forEach(k=>out[k]=base*(race.growth[k]||1)*(job.growth[k]||1));return out}
function attributeImpactText(k){const a=classArchetype(),d={str:`每+1力量：生命+5、防御+0.32、${a==='melee'?'近战攻击+2.35':a==='ranged'?'远程攻击+0.35':'不直接提高魔法攻击'}。`,int:`每+1智力：法力+5、${a==='magic'?'魔法攻击+2.25':'不直接提高当前职业攻击'}。`,dex:`每+1敏捷：原始暴击+0.32、平衡+0.45个百分点、速度+0.75、${a==='ranged'?'远程攻击+2.25':a==='melee'?'近战攻击+0.30':'不直接提高魔法攻击'}。`,will:`每+1意志：生命+3、法力+2、防御+1.35${a==='magic'?'、魔法攻击+0.25':''}。`,luck:'每+1幸运：原始暴击+0.24，并提高装备品质、Boss宠物和身份掉落相关判定。'};return d[k]}
function raceGrowthText(raceId=state.race){const r=RACES[raceId];return `${identityGrowthText(r)}｜种族特性【${r.traitName}】${r.traitDesc}`}
function styleGrowthText(styleId=state.style,raceId=state.race){const c=STYLES[styleId],a=c.archetype,formula=a==='melee'?'近战攻击 = 力量×2.35 + 敏捷×0.30 + 等级×2.00 + 装备攻击':a==='ranged'?'远程攻击 = 敏捷×2.25 + 力量×0.35 + 等级×2.00 + 装备攻击':'魔法攻击 = 智力×2.25 + 意志×0.25 + 等级×1.90 + 装备攻击';return `${identityGrowthText(c)}｜${formula}`}
function autoGrowth(){}
function gainXp(amount){const rp=rebirthProfile();amount=Math.round(amount*((raceTraitPowers().xp)||1)*(titleMods().xp||1)*rp.xp);state.xp+=amount;while(state.xp>=xpNeed()){state.xp-=xpNeed();state.level++;state.age+=.08;autoGrowth();syncSkills();const s=stats();state.hp=s.maxHp;state.mp=s.maxMp;log(`升级至Lv.${state.level}。当前属性按种族×职业模板实时重算。`,'sys','system')}}
function rarityRoll(luckBoost=0,useDanger=true){const luck=stats().luck+luckBoost,d=useDanger?dangerDropProfile(map().id):{progress:0,mythic:1},roll=Math.random()*100,baseMythic=Math.min(.16,.025+luck*.0005),mythic=Math.min(.24,baseMythic*d.mythic),legendary=Math.max(.05,(.55+luck*.012)-baseMythic)*(1+.45*d.progress),epic=Math.max(.2,(3+luck*.042)-(.55+luck*.012))*(1+.30*d.progress),rare=Math.max(1,(12+luck*.10)-(3+luck*.042))*(1+.20*d.progress),uncommon=Math.max(5,(35+luck*.18)-(12+luck*.10))*(1+.10*d.progress);let t=mythic;if(roll<t)return 5;t+=legendary;if(roll<t)return 4;t+=epic;if(roll<t)return 3;t+=rare;if(roll<t)return 2;t+=uncommon;if(roll<t)return 1;return 0}
function makeItem(dropMult=1,forcedWeaponType=null,forcedRarity=null,useDanger=true){const rarity=forcedRarity===null?rarityRoll((dropMult-1)*18,useDanger):clamp(Number(forcedRarity)||0,0,RARITIES.length-1),rd=RARITIES[rarity],slot=forcedWeaponType?'weapon':SLOTS[rnd(0,SLOTS.length-1)],sourceMap=map(),sourceThreat=threatTier(sourceMap.id),tier=equipmentTier(sourceMap,sourceThreat);let weaponType=null,base;if(slot==='weapon'){if(forcedWeaponType)weaponType=forcedWeaponType;else{const preferred=Object.entries(WEAPON_TYPES).filter(([,w])=>w.styles.includes(classArchetype())).map(([id])=>id),all=Object.keys(WEAPON_TYPES);weaponType=Math.random()<.68?preferred[rnd(0,preferred.length-1)]:all[rnd(0,all.length-1)]}base=WEAPON_NAMES[weaponType][rnd(0,WEAPON_NAMES[weaponType].length-1)]}else base=BASE_NAMES[slot][rnd(0,BASE_NAMES[slot].length-1)];const count=forcedWeaponType?1:1+rd.aff,statsObj={},affixes=[],focusChance=rarity>=5?.16:rarity===4?.08:rarity===3?.03:0,focusAffix=Math.random()<focusChance?AFFIXES[rnd(0,AFFIXES.length-1)]:null,repeatChance=rarity>=5?.62:rarity===4?.52:.42;for(let i=0;i<count;i++){const a=focusAffix&&Math.random()<repeatChance?focusAffix:AFFIXES[rnd(0,AFFIXES.length-1)],value=rollAffixValue(a,tier,rarity);statsObj[a.stat]=(statsObj[a.stat]||0)+value;affixes.push({name:a.name,stat:a.stat,value})}const tp=gearStatTierPower(tier),q=QUALITY_STAT_MULT[rarity]||1;if(slot==='weapon')statsObj.atk=(statsObj.atk||0)+Math.round((6+10*tp)*q);if(slot==='armor')statsObj.def=(statsObj.def||0)+Math.round((3+4.5*tp)*q);const score=gearTierScore(tier,rarity),sell=Math.round((8+score*.18)*(1+rarity*.35)),arcanes=slot==='amulet'?rollAmuletArcanes(rarity):[];return{id:'i'+state.nextItemId++,name:`${rd.name}${base}`,slot,rarity,stats:statsObj,affixes,arcanes,score,tier,itemLevel:tier,sourceMap:sourceMap.id,sourceMapName:sourceMap.name,sourceThreat,sell,locked:false,weaponType,refine:0,qualityCurveVersion:7}}
function itemScore(it){return gearScoreBreakdown(it).score}
function inventoryUpgradeDelta(it){const current=state.equipment[it.slot];return itemScore(it)-(current?itemScore(current):0)}
function sortedInventory(){return state.inventory.slice().sort((a,b)=>{const da=inventoryUpgradeDelta(a),db=inventoryUpgradeDelta(b),pa=da>0,pb=db>0;if(pa!==pb)return Number(pb)-Number(pa);if(da!==db)return db-da;const fa=gearScoreBreakdown(a).fit,fb=gearScoreBreakdown(b).fit;if(fa!==fb)return fb-fa;if(inferItemLevel(a)!==inferItemLevel(b))return inferItemLevel(b)-inferItemLevel(a);if(a.rarity!==b.rarity)return b.rarity-a.rarity;return itemScore(b)-itemScore(a)})}
function sellNonUpgradeItems(){const candidates=state.inventory.filter(it=>!it.locked&&inventoryUpgradeDelta(it)<=0);if(!candidates.length)return alert('按当前角色适配评分，没有可出售的无提升装备。锁定装备不会被处理。');const total=candidates.reduce((n,it)=>n+itemSellValue(it),0);if(!confirm(`按当前评分偏好一键出售${candidates.length}件没有角色适配评分提升的装备？\n获得${total}金币。\n\n改变评分偏好会改变“提升/无提升”的判断；锁定装备不会出售。`))return;const ids=new Set(candidates.map(it=>it.id));state.inventory=state.inventory.filter(it=>!ids.has(it.id));state.gold+=total;log(`按角色适配评分出售${candidates.length}件无提升装备，金币+${total}。`,'loot');render()}
function itemSellValue(it){return Math.max(1,Math.round((it.sell||1)*(1+(it.refine||0)*.12)*.35))}
function findItem(id){const inv=state.inventory.find(x=>x.id===id);if(inv)return inv;return Object.values(state.equipment).find(x=>x&&x.id===id)||null}
function refineCost(it){return Math.round((40+state.level*5)*(it.rarity+1)*Math.pow((it.refine||0)+1,2))}
