function dangerRise(m,cycle){
 const cap=threatCap(m.id),old=cycle.threatTier||0;cycle.dangerFail=Math.max(0,(cycle.dangerFail||0)-1.5);
 if(!Number.isFinite(cap)||old<cap){cycle.threatTier=old+1;const d=dangerDropProfile(m.id);log(`${m.name}危险度提升至T${cycle.threatTier}：战斗数值不变，仅提高掉落率${d.maxed?'（已达到最高有效掉落加成）':''}。`,'sys');}
 else log(`${m.name}已处于最高危险度T${cap}，战斗数值不变，继续享受最高掉落加成。`,'sys');
}
function dangerRecordWin(cycle,boss=false){cycle.dangerFail=Math.max(0,(cycle.dangerFail||0)-(boss?1.5:.35));}
function dangerRecordLoss(e,m,cycle){cycle.dangerFail=(cycle.dangerFail||0)+(e?.boss?2:1);if(cycle.dangerFail>=3&&cycle.threatTier>0){cycle.threatTier--;cycle.dangerFail=0;log(`${m.name}连续作战表现不佳，危险度降至T${cycle.threatTier}。敌人强度不变，但掉落加成降低。`,'sys');}}
function winBattle(){const e=state.enemy,m=map(),ratio=e.cp/Math.max(1,cp()),tm=titleMods(),globalMetric=state.metrics,mapMetric=ensureMetric(m.id),cycle=ensureBossCycle(m.id),danger=dangerDropProfile(m.id);state.totalWins++;state.totalKills++;registerPassiveBattleWin();state.killsByMap[m.id]=(state.killsByMap[m.id]||0)+1;if(ratio>1.35)state.highRiskWins++;const over=Math.max(0,state.level-(m.levels[1]+2)),levelPenalty=clamp(1-over*.08,.12,1);let xp=Math.max(1,Math.round((5+e.level*2.2)*clamp(ratio+m.mod,.65,2.2)*e.xp*((ratio>1.25?tm.riskXp:1)||1)*.61*levelPenalty));let gold=Math.max(1,Math.round((2+e.level*.75)*clamp(ratio+m.mod*.45,.55,2.6)*e.gold*(tm.gold||1)*.15*rebirthProfile().gold));gainXp(xp);state.gold+=gold;globalMetric.battles++;globalMetric.wins++;globalMetric.xp+=xp;globalMetric.gold+=gold;mapMetric.battles++;mapMetric.wins++;mapMetric.xp+=xp;mapMetric.gold+=gold;const dropChance=clamp(.18*e.drop*(tm.drop||1)*(1+stats().luck/300)*danger.gearDrop,.05,.90);if(Math.random()<dropChance){receiveItem(makeItem(e.drop));globalMetric.drops++;mapMetric.drops++;}tryDropSpecialSkill(e,m);if(e.boss)tryDropIdentity(e,m);const p=activePet();if(p)petGainXp(p,Math.max(1,Math.round(xp*.35)));log(`击败 ${e.name}，经验+${xp}，金币+${gold}。`,'win');if(e.boss){delete state.bossProgress[m.id];cycle.normalSinceBoss=0;cycle.retryCountdown=0;cycle.bossWins++;dangerRise(m,cycle);const after=dangerDropProfile(m.id),petChance=clamp((.20+stats().luck/500)*(tm.pet||1)*after.petDrop,.12,.70);if(Math.random()<petChance){const pet=createPet(m.pet,rollPetType(),MAPS.indexOf(m));receivePet(pet);}}else{cycle.normalSinceBoss++;dangerRecordWin(cycle,false);if(cycle.retryCountdown>0)cycle.retryCountdown--;}state.enemy=null;prepareNewBattle();checkTitles();save();refreshLiveUI('result');}
function loseBattle(){state.totalLosses++;const e=state.enemy,m=map(),globalMetric=state.metrics,mapMetric=ensureMetric(m.id),cycle=ensureBossCycle(m.id);globalMetric.battles++;globalMetric.losses++;mapMetric.battles++;mapMetric.losses++;log(`败给 ${e.name}。下一场战斗开始前恢复满状态。`,'lose');dangerRecordLoss(e,m,cycle);if(e&&e.boss){state.bossProgress[m.id]={active:true,hp:Math.max(1,e.hp),maxHp:e.maxHp};cycle.retryCountdown=2;log(`首领保留剩余生命。接下来穿插2场普通战斗后将自动再次遭遇。`,'sys');}state.enemy=null;prepareNewBattle();refreshLiveUI('result');}
function battleTick(){if(!state.started||!state.running)return;state.combatTurn=(state.combatTurn||0)+1;ensureEnemy();const s=stats(),e=state.enemy;if(!e)return;const heroFirst=s.speed>=e.speed;if(heroFirst){if(playerAlive()){playerAttack();if(e.hp<=0)return winBattle();}petTurn();if(e.hp<=0)return winBattle();enemyAttack();if(e.hp<=0)return winBattle();if(partyDefeated())return loseBattle();}else{enemyAttack();if(e.hp<=0)return winBattle();if(partyDefeated())return loseBattle();if(playerAlive()){playerAttack();if(e.hp<=0)return winBattle();}petTurn();if(e.hp<=0)return winBattle();}if(partyDefeated())return loseBattle();if(playerAlive())state.mp=Math.min(s.maxMp,state.mp+Math.max(1,Math.round(1+s.will*.025)));tickCompanionEffects(e);renderBattleOnly();}
function challengeBoss(){alert('Alpha 0.4已取消手动Boss挑战。区域Boss会在普通刷怪中随机出现，并设有保底机制。');}
function changeMap(id){state.mapId=id;state.enemy=null;prepareNewBattle();const m=map(),ratio=effectiveMapCp(m)/Math.max(1,cp());log(`前往 ${m.name}。地图没有进入门槛${ratio>2?'，但当前战力明显不足，预计会频繁战败':''}。下一场以满生命和满法力开始。`,'sys');render();}
function equipItem(id){const it=state.inventory.find(x=>x.id===id);if(!it)return;const old=state.equipment[it.slot];if(old)state.inventory.push(old);state.inventory=state.inventory.filter(x=>x.id!==id);state.equipment[it.slot]=it;const s=stats();state.hp=Math.min(state.hp,s.maxHp);state.mp=Math.min(state.mp,s.maxMp);render();}
function sellItem(id,doRender=true){const i=state.inventory.findIndex(x=>x.id===id);if(i<0)return;const it=state.inventory[i];if(it.locked)return;state.inventory.splice(i,1);state.gold+=itemSellValue(it);if(doRender)render();else refreshLiveUI('state');}
function unequip(slot){const it=state.equipment[slot];if(!it)return;if(state.inventory.length>=state.inventoryCapacity)return alert('背包已满');state.inventory.push(it);state.equipment[slot]=null;render()}
function toggleSkill(id){state.skills[id]=!state.skills[id];save();render()}
function checkTitles(){Object.entries(TITLES).forEach(([id,t])=>{if(!state.titlesUnlocked.includes(id)&&t.unlock(state)){state.titlesUnlocked.push(id);log(`解锁称号：${t.name}。`,'loot')}})}
function rebirth(){if(state.level<100)return alert('达到Lv.100后才能转生。');const laws=ensureRebirthLaws(),selected=state.pendingRebirthLaw||'war',available=Object.keys(REBIRTH_LAWS).filter(id=>(laws[id]||0)<REBIRTH_LAW_MAX),law=available.includes(selected)?selected:(available[0]||null),lawDef=law?REBIRTH_LAWS[law]:null,next=state.rebirths+1;if(!confirm(`执行第${next}次转生？\n\n当前身份：${RACES[state.race].name} · ${STYLES[state.style].name}\n${lawDef?`本次刻印：${lawDef.name}\n${lawDef.desc}`:'三项法则均已Lv.3，本次只获得轮回共鸣。'}\n\n种族/职业已改为永久解锁并可随时切换；转生不会删除任何身份、技能档案、装备或宠物。`))return;state.rebirths++;state.soul+=1;if(law)state.rebirthLaws[law]=(state.rebirthLaws[law]||0)+1;state.level=1;state.xp=0;state.age=16;state.base={str:6,int:6,dex:6,will:6,luck:6};state.growthCarry={str:0,int:0,dex:0,will:0,luck:0};state.mapId='meadow';state.enemy=null;state.killsByMap={};state.bossProgress={};state.bossCycles={};state.skillReadyAt={};state.combatTurn=0;syncSkills();const s=stats();state.hp=s.maxHp;state.mp=s.maxMp;checkTitles();log(`完成第${state.rebirths}次转生${law?`，刻印【${lawDef.name}】Lv.${state.rebirthLaws[law]}`:''}。所有身份与技能档案均保留。`,'important','important');save();render();}
function merchantGearCost(){return Math.round(70+state.level*16+MAPS.indexOf(map())*35+(state.shop?.gearBuys||0)*3)}
function buyMerchantGear(){const cost=merchantGearCost();if(state.gold<cost)return alert(`金币不足，需要${cost}。`);state.gold-=cost;state.shop.gearBuys++;receiveItem(makeItem(1.12,null,null,false));log(`向行商购买一件当前区域装备，金币-${cost}。`,'loot');render();}
function activePetTrainingCost(){const p=activePet();return p?50+p.level*22+Math.round((p.tier||1)*12):0}
function trainActivePet(){const p=activePet();if(!p)return alert('尚无出战宠物。');const cost=activePetTrainingCost();if(state.gold<cost)return alert(`金币不足，需要${cost}。`);state.gold-=cost;state.shop.petTraining++;const xp=22+p.level*8;petGainXp(p,xp);log(`${p.name}完成训练，获得宠物经验，金币-${cost}。阶级进化只能通过同类融合完成。`,'loot');render();}
function lowestPetAptitude(p){const a=migratePetAptitudes(p);return Object.keys(a).sort((x,y)=>gradeIndex(a[x])-gradeIndex(a[y]))[0]}
function aptitudeTrainingCosts(p){const key=lowestPetAptitude(p),score=gradeIndex(migratePetAptitudes(p)[key]);return{key,gold:120+score*55+p.level*10,dust:4+score*3};}
function trainPetAptitude(){const p=activePet();if(!p)return alert('尚无出战宠物。');const c=aptitudeTrainingCosts(p),a=migratePetAptitudes(p);if(gradeIndex(a[c.key])>=8)return alert('该宠物四项资质均已达到SSS。');if(state.gold<c.gold||state.petDust<c.dust)return alert(`需要${c.gold}金币和${c.dust}灵宠精华。`);state.gold-=c.gold;state.petDust-=c.dust;a[c.key]=gradeFromIndex(gradeIndex(a[c.key])+1);log(`${p.name}的${PET_APT_NAMES[c.key]}提升至${a[c.key]}，消耗${c.gold}金币和${c.dust}灵宠精华。`,'loot');render();}
function expandInventory(){const cost=300+(state.inventoryCapacity-40)*45;if(state.gold<cost)return alert(`金币不足，需要${cost}。`);state.gold-=cost;state.inventoryCapacity+=5;state.shop.inventoryUpgrades++;log(`装备背包扩建至${state.inventoryCapacity}格，金币-${cost}。`,'loot');render();}
function expandPetCapacity(){const cost=500+(state.petCapacity-12)*120;if(state.gold<cost)return alert(`金币不足，需要${cost}。`);state.gold-=cost;state.petCapacity+=2;state.shop.petUpgrades++;log(`宠物仓扩建至${state.petCapacity}格，金币-${cost}。`,'loot');render();}
function refineItem(id){const it=findItem(id);if(!it)return;if((it.refine||0)>=5)return alert('Alpha阶段精炼上限为+5。');const cost=refineCost(it);if(state.gold<cost)return alert(`金币不足，需要${cost}。`);state.gold-=cost;it.refine=(it.refine||0)+1;log(`${it.name}精炼至+${it.refine}，金币-${cost}。`,'loot');render();}
function save(){try{state.lastSave=Date.now();localStorage.setItem(SAVE_KEY,JSON.stringify(state))}catch{}}
const SAVE_SLOT_PREFIX='bwe-core-manual-slot-';
function saveSlot(n){save();localStorage.setItem(SAVE_SLOT_PREFIX+n,JSON.stringify(state));alert(`已保存到本地槽位${n}。`);updateResourceBar();}
function loadSlot(n){const raw=localStorage.getItem(SAVE_SLOT_PREFIX+n);if(!raw)return alert(`槽位${n}为空。`);if(!confirm(`读取槽位${n}？当前自动存档会被覆盖。`))return;localStorage.setItem(SAVE_KEY,raw);location.reload();}
function slotInfo(n){try{const d=JSON.parse(localStorage.getItem(SAVE_SLOT_PREFIX+n)||'null');return d?`${RACES[d.race]?.name||'?'}·${STYLES[d.style]?.name||'?'} Lv.${d.level||1} R${d.rebirths||0}｜${new Date(d.lastSave||0).toLocaleString()}`:'空';}catch{return'损坏'}}
function exportSave(){save();const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`bwe-save-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
