function itemText(it){const mult=1+(it.refine||0)*.08,tier=inferItemTier(it),names={str:'力量',int:'智力',dex:'敏捷',will:'意志',luck:'幸运',hp:'生命',mp:'法力',crit:'暴击',def:'防御',atk:'攻击'};let parts=[];if(Array.isArray(it.affixes)&&it.affixes.length){parts=it.affixes.map(a=>`${names[a.stat]||a.stat}+${Math.round((a.value||0)*mult)}`);if(it.slot==='weapon'&&(it.stats?.atk||0)>0)parts.unshift(`攻击+${Math.round((it.stats.atk||0)*mult)}`);if(it.slot==='armor'&&(it.stats?.def||0)>0){const affDef=it.affixes.filter(a=>a.stat==='def').reduce((n,a)=>n+(a.value||0),0),baseDef=Math.max(0,(it.stats.def||0)-affDef);if(baseDef>0)parts.unshift(`基础防御+${Math.round(baseDef*mult)}`)}}else parts=Object.entries(it.stats||{}).map(([k,v])=>`${names[k]||k}+${Math.round(v*mult)}`);return `${tier}阶${it.sourceMapName?` · ${it.sourceMapName}`:''}${it.sourceThreat?`T${it.sourceThreat}`:''}${it.refine?` / 精炼+${it.refine}`:''} / ${parts.join(' / ')}${it.weaponType?` / ${WEAPON_TYPES[it.weaponType].desc}`:''}${Array.isArray(it.arcanes)&&it.arcanes.length?` / ${it.arcanes.map(amuletArcaneText).join(' / ')}`:''}`}
function receiveItem(it){if(it.rarity<state.autoSell){state.gold+=itemSellValue(it);log(`自动出售 ${it.name}，金币+${itemSellValue(it)}。`,'loot');return}if(state.inventory.length>=state.inventoryCapacity){const low=state.inventory.filter(x=>!x.locked).sort((a,b)=>inventoryUpgradeDelta(a)-inventoryUpgradeDelta(b)||itemScore(a)-itemScore(b))[0];if(low&&inventoryUpgradeDelta(it)>inventoryUpgradeDelta(low)){sellItem(low.id,false);state.inventory.push(it);log(`背包已满，出售提升价值更低的装备并保留 ${it.name}。`,'loot')}else{state.gold+=itemSellValue(it);log(`背包已满，自动出售 ${it.name}。`,'loot')}}else{state.inventory.push(it);log(`获得 ${it.name}：${itemText(it)}。`,'loot')}}
function ensureBossCycle(id=state.mapId){state.bossCycles=state.bossCycles||{};const c=state.bossCycles[id]||{normalSinceBoss:0,retryCountdown:0,bossEncounters:0,bossWins:0,threatTier:0,dangerFail:0};if(c.threatTier===undefined)c.threatTier=c.bossWins||0;if(c.dangerFail===undefined)c.dangerFail=0;const cap=threatCap(id);if(Number.isFinite(cap))c.threatTier=Math.min(c.threatTier,cap);c.threatTier=Math.max(0,c.threatTier||0);state.bossCycles[id]=c;return c}
function threatCap(id=state.mapId){const m=MAPS.find(x=>x.id===id);return m?.threatCap??0}
function threatTier(id=state.mapId){return ensureBossCycle(id).threatTier||0}
function threatCapText(id=state.mapId){const cap=threatCap(id);return Number.isFinite(cap)?`上限T${cap}`:'无限记录 / T12满掉落'}
function dangerEffectiveCap(id=state.mapId){const cap=threatCap(id);return Number.isFinite(cap)?Math.max(1,cap):12}
function dangerProgress(id=state.mapId){return clamp(threatTier(id)/dangerEffectiveCap(id),0,1)}
function dangerDropProfile(id=state.mapId){const p=dangerProgress(id),maxed=p>=1,rp=rebirthProfile();return{progress:p,maxed,gearDrop:(1+.55*p)*rp.gearDrop,petDrop:(1+.35*p)*rp.petDrop,mythic:(1+1*p)*rp.mythic,mutation:(1+.60*p)*rp.mutation,special:(1+.25*p)*rp.special}}
function worldCombatScale(){return{cpMult:1,hp:1,atk:1,def:1,speed:1,levelBonus:0}}
function threatScale(id=state.mapId){const d=dangerDropProfile(id);return{tier:threatTier(id),cpMult:1,hp:1,atk:1,def:1,speed:1,reward:1,levelBonus:0,...d}}
function effectiveMapCp(mapDef){return Math.round(mapDef.cp*worldCombatScale().cpMult)}
function rollMonsterTitle(tier=0){return pickWeighted(MONSTER_TITLES)}
function bossCycleConfig(){const lv=Math.min(REBIRTH_LAW_MAX,ensureRebirthLaws().time||0),starts=[16,10,5,1],forced=[24,17,10,3],reduce=amuletPowers().bossNeed||0,start=Math.max(1,starts[lv]-reduce),forcedCount=Math.max(start,forced[lv]-reduce);return{level:lv,start,forced:forcedCount,amuletReduce:reduce}}
function bossEncounterChance(id=state.mapId){const c=ensureBossCycle(id),cfg=bossCycleConfig();if(state.bossProgress?.[id]?.active)return c.retryCountdown<=0?1:0;if(c.normalSinceBoss<cfg.start)return 0;const span=Math.max(1,cfg.forced-cfg.start),p=clamp((c.normalSinceBoss-cfg.start)/span,0,1);return clamp(.15+.35*p,.15,.50)}
function shouldEncounterBoss(id=state.mapId){const c=ensureBossCycle(id),progress=state.bossProgress?.[id],cfg=bossCycleConfig();if(progress?.active)return c.retryCountdown<=0;if(c.normalSinceBoss>=cfg.forced)return true;return Math.random()<bossEncounterChance(id)}
function bossEncounterText(id){const c=ensureBossCycle(id),progress=state.bossProgress?.[id],cfg=bossCycleConfig();if(progress?.active)return c.retryCountdown>0?`首领已受伤，将在${c.retryCountdown}场普通战斗后再次出现`:'受伤首领将在下一场自动重现';if(c.normalSinceBoss<cfg.start)return `时流Lv.${cfg.level}：再击败${cfg.start-c.normalSinceBoss}只普通怪后开始出现Boss｜${cfg.forced}只保底`;const chance=Math.round(bossEncounterChance(id)*100);return `时流Lv.${cfg.level}：当前Boss遭遇率${chance}%｜最多再${Math.max(0,cfg.forced-c.normalSinceBoss)}只普通怪保底`}
function makeEnemy(forceBoss=false){const m=map(),boss=forceBoss,w=worldCombatScale(),region=Math.max(1,m.cp/MAPS[0].cp),title=boss?{name:'区域首领：',atkMul:1.7,hpMul:16,defMul:1.25,xp:5,gold:7,drop:4.5}:rollMonsterTitle(),baseLevel=boss?m.levels[1]+2:rnd(m.levels[0],m.levels[1]),lv=baseLevel+w.levelBonus,rawHp=(72+lv*11)*Math.pow(region,.65),rawAtk=(11+lv*1.45)*Math.pow(region,.33),rawDef=(2.5+lv*.50)*Math.pow(region,.22),rawSpeed=(7+lv*.42)*Math.pow(region,.07),maxHp=Math.round(rawHp*(title.hpMul||1)*w.hp),atk=Math.round(rawAtk*(title.atkMul||1)*w.atk),def=Math.round(rawDef*(title.defMul||1)*w.def),speed=Math.round(rawSpeed*w.speed),titleCp=Math.sqrt((title.hpMul||1)*(title.atkMul||1))*Math.pow(title.defMul||1,.25);let enemy={id:'e'+Date.now()+Math.random(),name:`${title.name}${boss?m.boss:m.monsters[rnd(0,m.monsters.length-1)]}`,boss,title,level:lv,mapId:m.id,round:0,enraged:false,shield:0,threatTier:threatTier(m.id),maxHp,hp:maxHp,atk,def,speed,cp:Math.round(m.cp*w.cpMult*titleCp),xp:title.xp,gold:title.gold,drop:title.drop,rewardMult:1};if(boss&&m.id==='shore')enemy.def=Math.round(enemy.def*1.32);return enemy}
function ensureEnemy(){if(state.enemy)return;prepareNewBattle();const m=map(),cycle=ensureBossCycle(m.id),progress=state.bossProgress[m.id],boss=shouldEncounterBoss(m.id);if(boss){state.enemy=makeEnemy(true);if(progress?.active){state.enemy.maxHp=progress.maxHp;state.enemy.hp=progress.hp;log(`再次遭遇受伤的区域首领 ${state.enemy.name}，剩余生命${Math.round(state.enemy.hp)}/${state.enemy.maxHp}。`,'sys')}else{cycle.bossEncounters++;log(`稀有遭遇：区域首领 ${state.enemy.name} 出现。`,'sys')}}else state.enemy=makeEnemy(false)}
function activePet(){return state.pets.find(p=>p.id===state.activePetId)||null}
function setActivePet(id){const p=state.pets.find(x=>x.id===id);if(!p)return;if(state.running&&state.enemy)return alert('请先暂停战斗，再更换出战宠物。');state.activePetId=id;const ps=petStats(p);p.hp=ps.maxHp;p.battleTurns=0;p.fallen=false;state.temp=state.temp||{};state.temp.petGuardTurns=0;state.temp.petAtkBuffTurns=0;state.temp.petAtkBuff=0;log(`${p.name}成为新的出战宠物。`,'sys');render()}
function petAlive(p=activePet()){return !!p&&Number(p.hp)>0&&!p.fallen}
function petRoleStatus(p=activePet()){if(!p)return'';const type=PET_TYPES[p.type],sp=petSpeciesData(p);if(!petAlive(p))return`${sp.archetype} / ${type.role}｜本场已倒下`;if(p.type==='Defense'&&state.temp?.petGuardTurns>0)return`${sp.archetype} / ${type.role}｜守护剩余${state.temp.petGuardTurns}次受击`;if(p.type==='Balance'&&state.temp?.petAtkBuffTurns>0)return`${sp.archetype} / ${type.role}｜协同增益剩余${state.temp.petAtkBuffTurns}次攻击`;return `${sp.archetype} / ${type.role}`}
function enemyDefenseAgainstCompanion(e){let mult=1;if((e.petArmorBreakTurns||0)>0)mult*=.78;if((e.petWeakenTurns||0)>0)mult*=.90;return e.def*mult}
function markPetFallen(p){if(!p||p.fallen)return;p.hp=0;p.fallen=true;log(`${p.name}生命归零，本场暂时无法继续行动；下一场会自动复活。`,'lose')}
function tickCompanionEffects(e){if(!e)return;['petArmorBreakTurns','petWeakenTurns','skillArmorBreakTurns','speciesWeakenTurns','frostbiteTurns'].forEach(k=>{if((e[k]||0)>0)e[k]--})}
function petStats(p){const g=PET_TYPES[p.type].growth,a=migratePetAptitudes(p),tm=petTierMult(p.tier||1),xm=p.mutant?PET_MUTANT_MULT:1,rp=rebirthProfile(),ib=petTierInstincts(p),all=ib.all;return{maxHp:Math.round((p.baseHp+g.hp*p.level)*PET_GRADE_MULT[a.hp]*tm*xm*ib.hp*all),atk:Math.round((p.baseAtk+g.atk*p.level)*PET_GRADE_MULT[a.atk]*tm*xm*rp.petPower*(raceTraitPowers().petPower||1)*ib.atk*all),def:Math.round((p.baseDef+g.def*p.level)*PET_GRADE_MULT[a.def]*tm*xm*ib.def*all),magic:Math.round((p.baseMagic+g.magic*p.level)*PET_GRADE_MULT[a.magic]*tm*xm*rp.petPower*(raceTraitPowers().petPower||1)*ib.magic*all)}}
function rollPetType(){return PET_TYPE_IDS[Math.floor(Math.random()*PET_TYPE_IDS.length)]}
const PET_SPECIES_ICONS={'灰尾幼狼':'🐺','裂风幼狮':'🦁','树灵幼芽':'🌱','霜鳍幼兽':'🐬','王魂侍从':'👻','星核幼龙':'🐉'};
function petSpeciesIcon(p){return PET_SPECIES_ICONS[p?.name]||'🐾'}
function petPortrait(p){if(!p)return '';return `<div class="pet-portrait ${p.mutant?'mutant':''}" title="${p.name}">${petSpeciesIcon(p)}<small>${p.tier||1}阶</small></div>`}
function itemVisualClass(it){return it?.rarity===5?'mythic-item':''}
function petTypeIcon(type){return type==='Attack'?'🐺':type==='Defense'?'🐢':type==='Magic'?'🦉':'🦊'}
function petTypeCounts(){const counts={Attack:0,Defense:0,Magic:0,Balance:0};state.pets.forEach(p=>counts[p.type]=(counts[p.type]||0)+1);return counts}
function rollPetMutation(mapDef=map()){const luck=stats().luck,d=dangerDropProfile(mapDef.id),base=Math.min(.009,.0025+luck*.000012);return Math.random()<Math.min(.014,base*d.mutation)}
function petVariantLabel(p){return p?.mutant?'<span class="mutant-x">变异 X</span>':'普通种'}
function petKeepScore(p){return (p?.mutant?1000000:0)+petCombatPower(p)*10+petOverallScore(p)*100+(p?.level||1)*5+Math.round(petEvolutionProgress(p)*3000)}
