function dangerRise(m,cycle){
 const cap=threatCap(m.id),current=cycle.threatTier||0,limit=Number.isFinite(cap)?cap:999;cycle.dangerFail=Math.max(0,(cycle.dangerFail||0)-1.5);
 if(current<limit){cycle.threatTier=current+1;cycle.threatUnlocked=Math.max(cycle.threatUnlocked||0,cycle.threatTier);log(`击败${m.boss}，${m.name}危险度自动升至T${cycle.threatTier}。敌人和掉落同步增强。`,'important','important');}
 else log(`${m.name}已完成最高危险度T${cap}。`,'important','important');
}
function dangerRecordWin(cycle,boss=false){cycle.dangerFail=Math.max(0,(cycle.dangerFail||0)-(boss?1.5:.35));}
function dangerRecordLoss(e,m,cycle){cycle.dangerFail=(cycle.dangerFail||0)+(e?.boss?2:1);const current=cycle.threatTier||0;if(current>0){cycle.threatTier=current-1;log(`战斗失败，${m.name}危险度自动降至T${cycle.threatTier}；历史最高仍为T${cycle.threatUnlocked||current}。`,'important','important')}}
function maybeWarnBoss(m,cycle){if(cycle.warningIssued||state.bossProgress?.[m.id]?.active)return;const cfg=bossCycleConfig(),remaining=cfg.start-cycle.normalSinceBoss;if(remaining>0&&remaining<=3){cycle.warningIssued=true;log(`【Boss预告】${m.boss}最快将在${remaining}场普通战后出现。机制：${bossTacticalHint(m.id)}`,'important','important')}}
function grantFirstBossMilestone(m){state.firstBossMilestoneClaimed=true;state.starterProfessionPending=false;if(!state.pets.some(p=>p.name===m.pet)){const pet=createPet(m.pet,'Balance',0);pet.locked=true;if(state.pets.length>=state.petCapacity)state.petCapacity++;state.pets.push(pet);state.petCodex=state.petCodex||{};state.petCodex[m.pet]=(state.petCodex[m.pet]||0)+1;if(!state.activePetId)state.activePetId=pet.id;log(`【首领里程碑】${m.boss}留下了已锁定的${m.pet}，它已成为你的第一只伙伴。`,'important','important')}const pool=['melee','ranged','magic'],id=pool[rnd(0,pool.length-1)],job=STYLES[id];if(!state.unlockedClasses.includes(id))state.unlockedClasses.push(id);state.style=id;syncSkills();log(`【初阶职业印记】随机显现为${job.icon}${job.name}，职业已永久解锁并自动启用。`,'important','important');return false}
function claimStarterProfession(id){if(!state.starterProfessionPending||!['melee','ranged','magic'].includes(id))return;state.starterProfessionPending=false;if(!state.unlockedClasses.includes(id))state.unlockedClasses.push(id);state.running=true;switchClass(id);save();render(false)}
function winBattle(){const e=state.enemy,m=map(),ratio=e.cp/Math.max(1,cp()),tm=titleMods(),globalMetric=state.metrics,mapMetric=ensureMetric(m.id),cycle=ensureBossCycle(m.id),danger=dangerDropProfile(m.id),reward=Number(e.rewardMult||1),firstMilestone=e.boss&&m.id==='meadow'&&!state.firstBossMilestoneClaimed;state.totalWins++;state.totalKills++;registerPassiveBattleWin();state.killsByMap[m.id]=(state.killsByMap[m.id]||0)+1;if(ratio>1.35)state.highRiskWins++;const over=Math.max(0,state.level-(m.levels[1]+2)),levelPenalty=clamp(1-over*.08,.12,1);let xp=Math.max(1,Math.round((5+e.level*2.2)*clamp(ratio+m.mod,.65,2.2)*e.xp*((ratio>1.25?tm.riskXp:1)||1)*.61*levelPenalty*reward));let gold=Math.max(1,Math.round((2+e.level*.75)*clamp(ratio+m.mod*.45,.55,2.6)*e.gold*(tm.gold||1)*.15*rebirthProfile().gold*reward));gainXp(xp);state.gold+=gold;globalMetric.battles++;globalMetric.wins++;globalMetric.xp+=xp;globalMetric.gold+=gold;mapMetric.battles++;mapMetric.wins++;mapMetric.xp+=xp;mapMetric.gold+=gold;const dropChance=clamp(.18*e.drop*(tm.drop||1)*(1+stats().luck/300)*danger.gearDrop,.05,.90);if(Math.random()<dropChance){receiveItem(makeItem(e.drop));globalMetric.drops++;mapMetric.drops++;}if(e.boss&&!firstMilestone)tryDropIdentity(e,m);const p=activePet();if(p)petGainXp(p,Math.max(1,Math.round(xp*.35)));log(`击败 ${e.name}，经验+${xp}，金币+${gold}${reward>1?`（危险度收益×${reward.toFixed(2)}）`:''}。`,'win');let milestoneShown=false;if(e.boss){delete state.bossProgress[m.id];cycle.normalSinceBoss=0;cycle.retryCountdown=0;cycle.warningIssued=false;cycle.bossWins++;dangerRise(m,cycle);if(firstMilestone)milestoneShown=grantFirstBossMilestone(m);else{const after=dangerDropProfile(m.id),petChance=clamp((.20+stats().luck/500)*(tm.pet||1)*after.petDrop,.12,.70);if(Math.random()<petChance){const pet=createPet(m.pet,rollPetType(),MAPS.indexOf(m));receivePet(pet)}}}else{cycle.normalSinceBoss++;dangerRecordWin(cycle,false);if(cycle.retryCountdown>0)cycle.retryCountdown--;maybeWarnBoss(m,cycle)}state.enemy=null;prepareNewBattle();checkTitles();save();if(milestoneShown)render(false);else refreshLiveUI('result')}
function loseBattle(){state.totalLosses++;const e=state.enemy,m=map(),globalMetric=state.metrics,mapMetric=ensureMetric(m.id),cycle=ensureBossCycle(m.id);globalMetric.battles++;globalMetric.losses++;mapMetric.battles++;mapMetric.losses++;log(`败给 ${e.name}。下一场战斗开始前恢复满状态。`,'lose');dangerRecordLoss(e,m,cycle);if(e&&e.boss){const old=state.bossProgress[m.id],attempts=Number(old?.attempts||0)+1;if(attempts>=3){delete state.bossProgress[m.id];cycle.retryCountdown=0;cycle.normalSinceBoss=0;cycle.warningIssued=false;log(`【狩猎失败】3次挑战均未击败${m.boss}，首领已完全恢复并离开。${bossTacticalHint(m.id)}`,'important','important')}else{const startHp=Math.max(1,Number(e.huntStartHp||old?.hp||e.maxHp)),damage=Math.max(0,startHp-Math.max(0,e.hp)),keptHp=Math.max(1,Math.round(startHp-damage*.50)),hpRatio=clamp(keptHp/Math.max(1,e.maxHp),0,1);state.bossProgress[m.id]={active:true,hp:keptHp,maxHp:e.maxHp,hpRatio,attempts};cycle.retryCountdown=2;log(`Boss挑战${attempts}/3失败：本次伤害保留50%；危险度下降后，${m.boss}将按${Math.round(hpRatio*100)}%剩余生命重算，2场普通战后再战。`,'important','important')}}state.enemy=null;prepareNewBattle();refreshLiveUI('result')}
function battleTick(){if(!state.started||!state.running)return;state.combatTurn=(state.combatTurn||0)+1;ensureEnemy();const s=stats(),e=state.enemy;if(!e)return;const heroFirst=s.speed>=e.speed;if(heroFirst){if(playerAlive()){playerAttack();if(e.hp<=0)return winBattle();}petTurn();if(e.hp<=0)return winBattle();enemyAttack();if(e.hp<=0)return winBattle();if(partyDefeated())return loseBattle();}else{enemyAttack();if(e.hp<=0)return winBattle();if(partyDefeated())return loseBattle();if(playerAlive()){playerAttack();if(e.hp<=0)return winBattle();}petTurn();if(e.hp<=0)return winBattle();}if(partyDefeated())return loseBattle();if(playerAlive())state.mp=Math.min(s.maxMp,state.mp+Math.max(1,Math.round(1+s.will*.025)));tickCompanionEffects(e);renderBattleOnly();}
function challengeBoss(){alert('Alpha 0.38采用自动Boss狩猎：每轮最多3次挑战，失败只保留本次造成伤害的50%；三次失败后Boss完全恢复。');}
function changeMap(id){state.mapId=id;state.enemy=null;prepareNewBattle();const m=map(),ratio=effectiveMapCp(m)/Math.max(1,cp());log(`前往 ${m.name}。地图没有进入门槛${ratio>2?'，但当前战力明显不足，预计会频繁战败':''}。下一场以满生命和满法力开始。`,'sys');render();}
function equipItem(id){const it=state.inventory.find(x=>x.id===id);if(!it)return;const old=state.equipment[it.slot];if(old)state.inventory.push(old);state.inventory=state.inventory.filter(x=>x.id!==id);state.equipment[it.slot]=it;const s=stats();state.hp=Math.min(state.hp,s.maxHp);state.mp=Math.min(state.mp,s.maxMp);render();}
function sellItem(id,doRender=true){const i=state.inventory.findIndex(x=>x.id===id);if(i<0)return;const it=state.inventory[i];if(it.locked)return;state.inventory.splice(i,1);state.gold+=itemSellValue(it);if(doRender)render();else refreshLiveUI('state');}
function unequip(slot){const it=state.equipment[slot];if(!it)return;if(state.inventory.length>=state.inventoryCapacity)return alert('背包已满');state.inventory.push(it);state.equipment[slot]=null;render()}
function toggleSkill(id){state.skills[id]=!state.skills[id];save();render()}
function checkTitles(){Object.entries(TITLES).forEach(([id,t])=>{if(!state.titlesUnlocked.includes(id)&&t.unlock(state)){state.titlesUnlocked.push(id);log(`解锁称号：${t.name}。`,'loot')}})}
function rebirth(){if(state.level<100)return alert('达到Lv.100后才能转生。');const laws=ensureRebirthLaws(),selected=state.pendingRebirthLaw||'war',available=Object.keys(REBIRTH_LAWS).filter(id=>(laws[id]||0)<REBIRTH_LAW_MAX),law=available.includes(selected)?selected:(available[0]||null),lawDef=law?REBIRTH_LAWS[law]:null,next=state.rebirths+1;if(!confirm(`执行第${next}次转生？\n\n当前身份：${RACES[state.race].name} · ${STYLES[state.style].name}\n${lawDef?`本次刻印：${lawDef.name}\n${lawDef.desc}`:'三项法则均已Lv.3，本次只获得轮回共鸣。'}\n\n种族/职业已改为永久解锁并可随时切换；转生不会删除任何身份、技能档案、装备或宠物。`))return;state.rebirths++;state.soul+=1;if(law)state.rebirthLaws[law]=(state.rebirthLaws[law]||0)+1;state.level=1;state.xp=0;state.age=16;state.base={str:6,int:6,dex:6,will:6,luck:6};state.growthCarry={str:0,int:0,dex:0,will:0,luck:0};state.mapId='meadow';state.enemy=null;state.killsByMap={};state.bossProgress={};state.bossCycles={};state.skillReadyAt={};state.combatTurn=0;syncSkills();const s=stats();state.hp=s.maxHp;state.mp=s.maxMp;checkTitles();log(`完成第${state.rebirths}次转生${law?`，刻印【${lawDef.name}】Lv.${state.rebirthLaws[law]}`:''}。所有身份与技能档案均保留。`,'important','important');save();render();}
function merchantGearCost(){return Math.round(70+state.level*16+MAPS.indexOf(map())*35+(state.shop?.gearBuys||0)*3)}
function buyMerchantGear(){const cost=merchantGearCost();if(state.gold<cost)return alert(`金币不足，需要${cost}。`);state.gold-=cost;state.shop.gearBuys++;receiveItem(makeItem(1.12,null,null,false));log(`向行商购买一件当前区域装备，金币-${cost}。`,'loot');render();}
function activePetTrainingCost(){const p=activePet();return p?50+p.level*22+Math.round((p.tier||1)*12):0}
function trainActivePet(){const p=activePet();if(!p)return alert('尚无出战宠物。');const cost=activePetTrainingCost();if(state.gold<cost)return alert(`金币不足，需要${cost}。`);state.gold-=cost;state.shop.petTraining++;const xp=22+p.level*8;petGainXp(p,xp);log(`${p.name}完成训练，获得宠物经验，金币-${cost}。阶级进化只能通过同类融合完成。`,'loot');render();}
function lowestPetAptitude(p){const a=migratePetAptitudes(p);return Object.keys(a).sort((x,y)=>gradeIndex(a[x])-gradeIndex(a[y]))[0]}
function aptitudeTrainingCosts(p){const key=lowestPetAptitude(p),score=gradeIndex(migratePetAptitudes(p)[key]);return{key,gold:120+score*55+p.level*10,dust:4+score*3};}
function trainPetAptitude(){const p=activePet();if(!p)return alert('尚无出战宠物。');const c=aptitudeTrainingCosts(p),a=migratePetAptitudes(p);if(gradeIndex(a[c.key])>=8)return alert('该宠物四项资质均已达到SSS。');if(state.gold<c.gold||state.petDust<c.dust)return alert(`需要${c.gold}金币和${c.dust}灵宠精华。`);state.gold-=c.gold;state.petDust-=c.dust;a[c.key]=gradeFromIndex(gradeIndex(a[c.key])+1);log(`${p.name}的${PET_APT_NAMES[c.key]}提升至${a[c.key]}，消耗${c.gold}金币和${c.dust}灵宠精华。`,'loot');render();}
function expandInventory(){const cost=300+(state.inventoryCapacity-40)*45;if(state.gold<cost)return alert(`金币不足，需要${cost}。`);state.gold-=cost;state.inventoryCapacity+=5;state.shop.inventoryUpgrades++;log(`装备背包扩建至${state.inventoryCapacity}格，金币-${cost}。`,'loot');render();}
function expandPetCapacity(){const cost=500+(state.petCapacity-12)*120;if(state.gold<cost)return alert(`金币不足，需要${cost}。`);state.gold-=cost;state.petCapacity+=2;state.shop.petUpgrades++;log(`宠物仓扩建至${state.petCapacity}格，金币-${cost}。`,'loot');render();}
function refineItem(id){const it=findItem(id);if(!it)return;if((it.refine||0)>=5)return alert('Alpha阶段精炼上限为+5。');const cost=refineCost(it);if(state.gold<cost)return alert(`金币不足，需要${cost}。`);state.gold-=cost;it.refine=(it.refine||0)+1;log(`${it.name}精炼至+${it.refine}，金币-${cost}。`,'loot');render();}
function save(){try{state.lastSave=Date.now();localStorage.setItem(SAVE_KEY,JSON.stringify(state))}catch{}}
const SAVE_SLOT_PREFIX='bwe-core-manual-slot-';
function saveSlot(n){save();localStorage.setItem(SAVE_SLOT_PREFIX+n,JSON.stringify(state));alert(`已保存到本地槽位${n}。`);updateResourceBar();}
function loadSlot(n){const raw=localStorage.getItem(SAVE_SLOT_PREFIX+n);if(!raw)return alert(`槽位${n}为空。`);if(!confirm(`读取槽位${n}？当前自动存档会被覆盖。`))return;localStorage.setItem(SAVE_KEY,raw);location.reload();}
function slotInfo(n){try{const d=JSON.parse(localStorage.getItem(SAVE_SLOT_PREFIX+n)||'null');return d?`${RACES[d.race]?.name||'?'}·${STYLES[d.style]?.name||'?'} Lv.${d.level||1} R${d.rebirths||0}｜${new Date(d.lastSave||0).toLocaleString()}`:'空';}catch{return'损坏'}}
function exportSave(){save();const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`bwe-save-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
